<?php
 /*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 * All rights reserved.
 *
 * This source code is licensed under the license found in the
 * LICENSE file in the root directory of this source tree.
 */

namespace FacebookAds\Object\Fields;

use FacebookAds\Enum\AbstractEnum;

/**
 * This class is auto-generated.
 *
 * For any issues or feature requests related to this class, please let us know
 * on github and we'll fix in our codegen framework. We'll not be able to accept
 * pull request for this class.
 *
 */

class AdAccountGetFields extends AbstractEnum {

  const ACCOUNT_CONTROLS = 'account_controls';
  const ACCOUNT_CURRENCY_RATIO_TO_USD = 'account_currency_ratio_to_usd';
  const ACCOUNT_ID = 'account_id';
  const ACCOUNT_STATUS = 'account_status';
  const ACTIVE_BILLING_DATE_PREFERENCE = 'active_billing_date_preference';
  const ACTIVITIES = 'activities';
  const AD_ACCOUNT_PROMOTABLE_OBJECTS = 'ad_account_promotable_objects';
  const AD_COLUMN_SIZES = 'ad_column_sizes';
  const AD_LIMITS_INSIGHTS = 'ad_limits_insights';
  const ADCREATIVES = 'adcreatives';
  const ADDRAFTS = 'addrafts';
  const ADIMAGES = 'adimages';
  const ADLABELS = 'adlabels';
  const ADRULES_COUNT_BY_TYPE = 'adrules_count_by_type';
  const ADRULES_HISTORY = 'adrules_history';
  const ADRULES_LIBRARY = 'adrules_library';
  const ADS = 'ads';
  const ADS_PAUSED = 'ads_paused';
  const ADS_VOLUME = 'ads_volume';
  const ADSETS = 'adsets';
  const ADSPAYMENTCYCLE = 'adspaymentcycle';
  const ADSPIXELS = 'adspixels';
  const ADTRUST_DSL = 'adtrust_dsl';
  const ADVERTISABLE_APPLICATIONS = 'advertisable_applications';
  const ADVIDEOS = 'advideos';
  const AGE = 'age';
  const AGENCIES = 'agencies';
  const AGENCY_CLIENT_DECLARATION = 'agency_client_declaration';
  const AGENCY_FEE_CONFIG = 'agency_fee_config';
  const AI_GENERATED_FEATURES_TEST_FRAMEWORK_ENROLLED = 'ai_generated_features_test_framework_enrolled';
  const ALL_CAPABILITIES = 'all_capabilities';
  const ALL_PAYMENT_METHODS = 'all_payment_methods';
  const AM_ONESHOP_SETTINGS = 'am_oneshop_settings';
  const AMOUNT_SPENT = 'amount_spent';
  const AMOUNT_SPENT_HISTORY = 'amount_spent_history';
  const APPLICATIONS = 'applications';
  const APPLIED_PUBLISHER_BLOCK_LISTS = 'applied_publisher_block_lists';
  const ARCHIVED_ADGROUP_COUNT = 'archived_adgroup_count';
  const ARCHIVED_CAMPAIGN_COUNT = 'archived_campaign_count';
  const ARCHIVED_CAMPAIGN_GROUP_COUNT = 'archived_campaign_group_count';
  const ASSET_FEED_SPEC_FROM_EXISTING_POST = 'asset_feed_spec_from_existing_post';
  const ASSET_FEED_SPEC_FROM_INSTAGRAM_MEDIA = 'asset_feed_spec_from_instagram_media';
  const ASSET_SCORE = 'asset_score';
  const ASSIGNED_PARTNERS = 'assigned_partners';
  const ATTR_WINDOW_DEPRECATION_GROUP = 'attr_window_deprecation_group';
  const AUTH_FLOW_FOR_TRUST_TIER_STATE = 'auth_flow_for_trust_tier_state';
  const AUTHORIZED_COUNTRY_FOR_POLITICAL_ADS = 'authorized_country_for_political_ads';
  const AUTOMATIC_CREATIVE_OPTIMIZATION_TEST_FRAMEWORK_ENROLLED = 'automatic_creative_optimization_test_framework_enrolled';
  const AVERAGE_DAILY_CAMPAIGN_BUDGET = 'average_daily_campaign_budget';
  const AVERAGE_DAILY_CAMPAIGN_GROUP_BUDGET = 'average_daily_campaign_group_budget';
  const AVERAGE_LIFETIME_CAMPAIGN_BUDGET = 'average_lifetime_campaign_budget';
  const AVERAGE_LIFETIME_CAMPAIGN_GROUP_BUDGET = 'average_lifetime_campaign_group_budget';
  const BALANCE = 'balance';
  const BRAND_SAFETY_CONTENT_FILTER_LEVELS = 'brand_safety_content_filter_levels';
  const BRAND_SAFETY_EXCLUDED_TOPICS = 'brand_safety_excluded_topics';
  const BUSINESS = 'business';
  const BUSINESS_AD_ACCOUNT_REQUESTS = 'business_ad_account_requests';
  const BUSINESS_CITY = 'business_city';
  const BUSINESS_COUNTRY_CODE = 'business_country_code';
  const BUSINESS_NAME = 'business_name';
  const BUSINESS_RESTRICTION_REASON = 'business_restriction_reason';
  const BUSINESS_STATE = 'business_state';
  const BUSINESS_STREET = 'business_street';
  const BUSINESS_STREET2 = 'business_street2';
  const BUSINESS_VERIFICATION_STATUS = 'business_verification_status';
  const BUSINESS_ZIP = 'business_zip';
  const BUSINESSPROJECTS = 'businessprojects';
  const CALL_ADS_AD_ACCOUNT_SIMILAR_ADVERTISER_BUDGET_RECOMMENDATION = 'call_ads_ad_account_similar_advertiser_budget_recommendation';
  const CALL_ADS_SIMILAR_ADVERTISER_BUDGET_RECOMMENDATION = 'call_ads_similar_advertiser_budget_recommendation';
  const CAMPAIGN_GROUP_WITH_CBO = 'campaign_group_with_cbo';
  const CAMPAIGNS = 'campaigns';
  const CAN_BYPASS_FS_CHECK = 'can_bypass_fs_check';
  const CAN_CREATE_BRAND_LIFT_STUDY = 'can_create_brand_lift_study';
  const CAN_PAY_NOW = 'can_pay_now';
  const CAN_REMOVE_PAYMENT_METHODS = 'can_remove_payment_methods';
  const CAN_REPAY_NOW = 'can_repay_now';
  const CAN_SEE_COLLABORATIVE_ADS_REPORTING = 'can_see_collaborative_ads_reporting';
  const CAPABILITIES = 'capabilities';
  const CONNECTED_INSTAGRAM_ACCOUNTS = 'connected_instagram_accounts';
  const CPAS_CAMPAIGN_DEFAULT_BUDGET = 'cpas_campaign_default_budget';
  const CPAS_CAMPAIGN_GROUP_DEFAULT_BUDGET = 'cpas_campaign_group_default_budget';
  const CREATED_TIME = 'created_time';
  const CREATION_PACKAGES = 'creation_packages';
  const CTWA_SMB_ENFORCING_DAYS_LEFT = 'ctwa_smb_enforcing_days_left';
  const CTX_ADVERTISER_SABR_LIFETIME_DURATION_RECOMMENDATION = 'ctx_advertiser_sabr_lifetime_duration_recommendation';
  const CTX_DFO_OBJECTIVE_DEFAULTS = 'ctx_dfo_objective_defaults';
  const CTX_FLEXIBLE_FORMAT_TARGETING = 'ctx_flexible_format_targeting';
  const CURRENCY = 'currency';
  const CURRENT_ADDRAFTS = 'current_addrafts';
  const CURRENT_UNBILLED_SPEND = 'current_unbilled_spend';
  const CURRENT_UNPAID_UNREPAID_INVOICE = 'current_unpaid_unrepaid_invoice';
  const CUSTOM_AUDIENCE_INFO = 'custom_audience_info';
  const CUSTOMAUDIENCES = 'customaudiences';
  const CUSTOMCONVERSIONS = 'customconversions';
  const CUSTOMER_PO_NUMBER = 'customer_po_number';
  const DAILY_SPEND_LIMIT = 'daily_spend_limit';
  const DCAF = 'dcaf';
  const DEFAULT_DSA_BENEFICIARY = 'default_dsa_beneficiary';
  const DEFAULT_DSA_PAYOR = 'default_dsa_payor';
  const DEFAULT_UNIFIED_ATTRIBUTION_SPEC = 'default_unified_attribution_spec';
  const DEFAULT_VALUES = 'default_values';
  const DISABLE_REASON = 'disable_reason';
  const DOMAIN_AND_SITE_LINKS = 'domain_and_site_links';
  const DSA_RECOMMENDATIONS = 'dsa_recommendations';
  const DYNAMIC_PROBATION_DSL = 'dynamic_probation_dsl';
  const END_ADVERTISER = 'end_advertiser';
  const END_ADVERTISER_NAME = 'end_advertiser_name';
  const EXISTING_CUSTOMERS = 'existing_customers';
  const EXPIRED_FUNDING_SOURCE_DETAILS = 'expired_funding_source_details';
  const EXTENDED_CREDIT = 'extended_credit';
  const EXTENDED_CREDIT_INFO = 'extended_credit_info';
  const EXTENDED_CREDIT_INVOICE_GROUP = 'extended_credit_invoice_group';
  const FAILED_DELIVERY_CHECKS = 'failed_delivery_checks';
  const FB_ENTITY = 'fb_entity';
  const FLEX_SINGLE_OBJECTIVE = 'flex_single_objective';
  const FUNDING_SOURCE = 'funding_source';
  const FUNDING_SOURCE_DETAILS = 'funding_source_details';
  const GENERATEPREVIEWS = 'generatepreviews';
  const HAS_ACTIVE_SKAN_CAMPAIGN_GROUPS = 'has_active_skan_campaign_groups';
  const HAS_COMBO_CARDS_ON_FILE = 'has_combo_cards_on_file';
  const HAS_EXTENDED_CREDIT = 'has_extended_credit';
  const HAS_MIGRATED_PERMISSIONS = 'has_migrated_permissions';
  const HAS_PAGE_AUTHORIZED_ADACCOUNT = 'has_page_authorized_adaccount';
  const HAS_PERSONAL_ACCESS = 'has_personal_access';
  const HAS_PURCHASE_OPTIMIZATION_ELIGIBLE_PAGE = 'has_purchase_optimization_eligible_page';
  const HAS_REPAY_PROCESSING_INVOICES = 'has_repay_processing_invoices';
  const HAS_STARTED_PURCHASE_OPTIMIZED_CTM_AD_WITHIN_1D = 'has_started_purchase_optimized_ctm_ad_within_1d';
  const HAS_VALUE_RULE_SET = 'has_value_rule_set';
  const ID = 'id';
  const IF_VIEWER_HAS_PERMISSION_TO_ADVERTISE = 'if_viewer_has_permission_to_advertise';
  const INCREMENTAL_CONVERSION_OPTIMIZATION_AD_STUDIES = 'incremental_conversion_optimization_ad_studies';
  const INSTAGRAM_ACCOUNTS = 'instagram_accounts';
  const INVOICING_EMAILS = 'invoicing_emails';
  const IOS_FOURTEEN_CAMPAIGN_LIMITS = 'ios_fourteen_campaign_limits';
  const IS_ATTRIBUTION_SPEC_SYSTEM_DEFAULT = 'is_attribution_spec_system_default';
  const IS_BA_SKIP_DELAYED_ELIGIBLE = 'is_ba_skip_delayed_eligible';
  const IS_BIZ_MIGRATION_ELIGIBLE = 'is_biz_migration_eligible';
  const IS_BR_ENTITY_ACCOUNT = 'is_br_entity_account';
  const IS_BUSINESS_ALLOWED_TO_ADVERTISE = 'is_business_allowed_to_advertise';
  const IS_BUSINESS_VERIFICATION_ELIGIBLE = 'is_business_verification_eligible';
  const IS_CLOSED_BY_ADVERTISER_COMPROMISE_BOT = 'is_closed_by_advertiser_compromise_bot';
  const IS_COLLABORATIVE_ADS_AD_ACCOUNT = 'is_collaborative_ads_ad_account';
  const IS_CTX_ADVERTISER = 'is_ctx_advertiser';
  const IS_DIRECT_DEALS_ENABLED = 'is_direct_deals_enabled';
  const IS_DISABLED_UMBRELLA = 'is_disabled_umbrella';
  const IS_ELIGIBLE_FOR_ADVANTAGE_PLUS_CREATIVE_REGULATED_CATEGORY = 'is_eligible_for_advantage_plus_creative_regulated_category';
  const IS_EXPANDED_SHOPLESS_AWPT_ELIGIBLE = 'is_expanded_shopless_awpt_eligible';
  const IS_IN_3DS_AUTHORIZATION_ENABLED_MARKET = 'is_in_3ds_authorization_enabled_market';
  const IS_MI_BILLING_INFO_UPDATED = 'is_mi_billing_info_updated';
  const IS_MM_LITE_API_ENABLED = 'is_mm_lite_api_enabled';
  const IS_NEW_ADVERTISER = 'is_new_advertiser';
  const IS_NOTIFICATIONS_ENABLED = 'is_notifications_enabled';
  const IS_OBA_OPT_OUT = 'is_oba_opt_out';
  const IS_OMNICHANNEL_CAMPAIGN_ELIGIBLE = 'is_omnichannel_campaign_eligible';
  const IS_PAGELESS_CTWA_ELIGIBLE = 'is_pageless_ctwa_eligible';
  const IS_PENDING_NUMBERS_EXPOSURE_FLAG_ENABLED = 'is_pending_numbers_exposure_flag_enabled';
  const IS_PERSONAL = 'is_personal';
  const IS_PINLESS_DEBIT_ELIGIBLE = 'is_pinless_debit_eligible';
  const IS_PLACEMENT_SOFT_OPT_OUT_ENABLED = 'is_placement_soft_opt_out_enabled';
  const IS_PREPAY_ACCOUNT = 'is_prepay_account';
  const IS_RETAIL_MEDIA_NETWORK = 'is_retail_media_network';
  const IS_SHOPLESS_AWPT_ELIGIBLE = 'is_shopless_awpt_eligible';
  const IS_TAX_ID_REQUIRED = 'is_tax_id_required';
  const IS_TIER_0 = 'is_tier_0';
  const IS_TIER_0_FULL = 'is_tier_0_full';
  const IS_TIER_1 = 'is_tier_1';
  const IS_TIER_RESTRICTED = 'is_tier_restricted';
  const IS_UPDATE_TIMEZONE_CURRENCY_TOO_RECENTLY = 'is_update_timezone_currency_too_recently';
  const IS_USER_ALLOWED_TO_ADVERTISE = 'is_user_allowed_to_advertise';
  const IS_USING_HIGHER_DAILY_FLEX_RATE = 'is_using_higher_daily_flex_rate';
  const IS_VALUE_RULES_SMART_DEFAULT_ON = 'is_value_rules_smart_default_on';
  const IS_WA_CLOUD_API_USER = 'is_wa_cloud_api_user';
  const IS_YOUTH_ADS_PAO_BASIC_ADVERTISER = 'is_youth_ads_pao_basic_advertiser';
  const IS_YOUTH_ADS_PAO_BASIC_ADVERTISER_ANNOUNCEMENT_ELIGIBLE = 'is_youth_ads_pao_basic_advertiser_announcement_eligible';
  const LAST_SPEND_TIME = 'last_spend_time';
  const LAST_USED_TIME = 'last_used_time';
  const LIABLE_ADDRESS = 'liable_address';
  const LIABLE_ADDRESSES = 'liable_addresses';
  const LIVE_VIDEO_ADVERTISER_DETAILS = 'live_video_advertiser_details';
  const MARKETING_MESSAGE_ENABLEMENT_STATUS = 'marketing_message_enablement_status';
  const MARKETING_MESSAGES_SETTINGS = 'marketing_messages_settings';
  const MAX_BID = 'max_bid';
  const MAX_BILLING_THRESHOLD = 'max_billing_threshold';
  const MAYBE_PAC_INTERNAL_POST_FROM_PRIMARY_POST = 'maybe_pac_internal_post_from_primary_post';
  const MEDIA_AGENCY = 'media_agency';
  const MIN_BILLING_THRESHOLD = 'min_billing_threshold';
  const MIN_CAMPAIGN_GROUP_SPEND_CAP = 'min_campaign_group_spend_cap';
  const MIN_DAILY_BUDGET = 'min_daily_budget';
  const MIN_LIVE_BOOSTING_BUDGET = 'min_live_boosting_budget';
  const MIN_PAYMENT = 'min_payment';
  const MINIMUM_BUDGETS = 'minimum_budgets';
  const MODELED_REPORTING_TYPE = 'modeled_reporting_type';
  const MOO_DEFAULT_CONVERSION_BID = 'moo_default_conversion_bid';
  const NAME = 'name';
  const NEXT_BILL_DATE = 'next_bill_date';
  const OFFSITE_PIXELS_TOS_ACCEPTED = 'offsite_pixels_tos_accepted';
  const ONBEHALF_REQUESTS = 'onbehalf_requests';
  const OPPORTUNITY_SCORE = 'opportunity_score';
  const OPPORTUNITY_SCORE_WEIGHT = 'opportunity_score_weight';
  const OWNER = 'owner';
  const OWNER_BUSINESS = 'owner_business';
  const PAGE_AUTHORIZED_COUNTRY_FOR_POLITICAL_ADS = 'page_authorized_country_for_political_ads';
  const PAGES_IN_AUTHORIZATIONS = 'pages_in_authorizations';
  const PARTNER = 'partner';
  const PAYMENT_OPTIONS = 'payment_options';
  const PENDING_BILLING_DATE_PREFERENCE = 'pending_billing_date_preference';
  const PREPAY_ACCOUNT_BALANCE = 'prepay_account_balance';
  const PROMOTION_METADATA = 'promotion_metadata';
  const PROMOTION_METADATA_LIVE_CRAWL = 'promotion_metadata_live_crawl';
  const PUBLISHER_BLOCK_LISTS = 'publisher_block_lists';
  const REACHESTIMATE = 'reachestimate';
  const REACHFREQUENCYPREDICTIONS = 'reachfrequencypredictions';
  const RECOMMENDATIONS = 'recommendations';
  const RF_SPEC = 'rf_spec';
  const SALES_SEGMENT_V2 = 'sales_segment_v2';
  const SAVED_AUDIENCES = 'saved_audiences';
  const SEGMENT = 'segment';
  const SEND_BILL_TO_ADDRESS = 'send_bill_to_address';
  const SEND_BILL_TO_ADDRESSES = 'send_bill_to_addresses';
  const SHOW_IMPROVED_BOLETO = 'show_improved_boleto';
  const SHOW_SAC_CAMPAIGN_GROUP_INPUT = 'show_sac_campaign_group_input';
  const SITE_LINKS_LIVE_CRAWL = 'site_links_live_crawl';
  const SOLD_TO_ADDRESS = 'sold_to_address';
  const SOLD_TO_ADDRESSES = 'sold_to_addresses';
  const SPEND_CAP = 'spend_cap';
  const SPEND_CAP_HISTORY = 'spend_cap_history';
  const SPENDLIMITS = 'spendlimits';
  const STORED_BALANCE_STATUS = 'stored_balance_status';
  const SUBSCRIBED_APPS = 'subscribed_apps';
  const TARGETINGBROWSE = 'targetingbrowse';
  const TARGETINGSEARCH = 'targetingsearch';
  const TARGETINGSUGGESTIONS = 'targetingsuggestions';
  const TAX_COUNTRY = 'tax_country';
  const TAX_EXEMPT = 'tax_exempt';
  const TAX_ID = 'tax_id';
  const TAX_ID_STATUS = 'tax_id_status';
  const TAX_ID_TYPE = 'tax_id_type';
  const TIMEZONE_ID = 'timezone_id';
  const TIMEZONE_NAME = 'timezone_name';
  const TIMEZONE_OFFSET_HOURS_UTC = 'timezone_offset_hours_utc';
  const TOS_ACCEPTED = 'tos_accepted';
  const TOTAL_PREPAY_BALANCE = 'total_prepay_balance';
  const TRACKING = 'tracking';
  const TRANSACTIONS = 'transactions';
  const USER_ACCESS_EXPIRE_TIME = 'user_access_expire_time';
  const USER_ROLE = 'user_role';
  const USER_SETTINGS = 'user_settings';
  const USER_TASKS = 'user_tasks';
  const USER_TOS_ACCEPTED = 'user_tos_accepted';
  const USERS = 'users';
  const VALUE_RULE_SET = 'value_rule_set';
  const VIEWABLE_BUSINESS = 'viewable_business';
  const VIEWABLE_BUSINESSES = 'viewable_businesses';

  public function getFieldTypes() {
    return array(
      'account_controls' => 'object',
      'account_currency_ratio_to_usd' => 'float',
      'account_id' => 'string',
      'account_status' => 'int',
      'active_billing_date_preference' => 'object',
      'activities' => 'object',
      'ad_account_promotable_objects' => 'object',
      'ad_column_sizes' => 'object',
      'ad_limits_insights' => 'object',
      'adcreatives' => 'object',
      'addrafts' => 'object',
      'adimages' => 'object',
      'adlabels' => 'object',
      'adrules_count_by_type' => 'object',
      'adrules_history' => 'object',
      'adrules_library' => 'object',
      'ads' => 'object',
      'ads_paused' => 'bool',
      'ads_volume' => 'object',
      'adsets' => 'object',
      'adspaymentcycle' => 'object',
      'adspixels' => 'object',
      'adtrust_dsl' => 'float',
      'advertisable_applications' => 'object',
      'advideos' => 'object',
      'age' => 'float',
      'agencies' => 'object',
      'agency_client_declaration' => 'object',
      'agency_fee_config' => 'object',
      'ai_generated_features_test_framework_enrolled' => 'bool',
      'all_capabilities' => 'list<string>',
      'all_payment_methods' => 'object',
      'am_oneshop_settings' => 'object',
      'amount_spent' => 'string',
      'amount_spent_history' => 'list<object>',
      'applications' => 'object',
      'applied_publisher_block_lists' => 'object',
      'archived_adgroup_count' => 'int',
      'archived_campaign_count' => 'int',
      'archived_campaign_group_count' => 'int',
      'asset_feed_spec_from_existing_post' => 'object',
      'asset_feed_spec_from_instagram_media' => 'object',
      'asset_score' => 'float',
      'assigned_partners' => 'object',
      'attr_window_deprecation_group' => 'string',
      'auth_flow_for_trust_tier_state' => 'AuthFlowForTrustTierState',
      'authorized_country_for_political_ads' => 'AuthorizedCountryForPoliticalAds',
      'automatic_creative_optimization_test_framework_enrolled' => 'bool',
      'average_daily_campaign_budget' => 'string',
      'average_daily_campaign_group_budget' => 'string',
      'average_lifetime_campaign_budget' => 'string',
      'average_lifetime_campaign_group_budget' => 'string',
      'balance' => 'string',
      'brand_safety_content_filter_levels' => 'list<string>',
      'brand_safety_excluded_topics' => 'list<BrandSafetyExcludedTopics>',
      'business' => 'object',
      'business_ad_account_requests' => 'object',
      'business_city' => 'string',
      'business_country_code' => 'string',
      'business_name' => 'string',
      'business_restriction_reason' => 'BusinessRestrictionReason',
      'business_state' => 'string',
      'business_street' => 'string',
      'business_street2' => 'string',
      'business_verification_status' => 'BusinessVerificationStatus',
      'business_zip' => 'string',
      'businessprojects' => 'object',
      'call_ads_ad_account_similar_advertiser_budget_recommendation' => 'float',
      'call_ads_similar_advertiser_budget_recommendation' => 'object',
      'campaign_group_with_cbo' => 'object',
      'campaigns' => 'object',
      'can_bypass_fs_check' => 'bool',
      'can_create_brand_lift_study' => 'bool',
      'can_pay_now' => 'bool',
      'can_remove_payment_methods' => 'bool',
      'can_repay_now' => 'bool',
      'can_see_collaborative_ads_reporting' => 'bool',
      'capabilities' => 'list<string>',
      'connected_instagram_accounts' => 'object',
      'cpas_campaign_default_budget' => 'int',
      'cpas_campaign_group_default_budget' => 'int',
      'created_time' => 'mixed',
      'creation_packages' => 'object',
      'ctwa_smb_enforcing_days_left' => 'int',
      'ctx_advertiser_sabr_lifetime_duration_recommendation' => 'int',
      'ctx_dfo_objective_defaults' => 'object',
      'ctx_flexible_format_targeting' => 'bool',
      'currency' => 'string',
      'current_addrafts' => 'object',
      'current_unbilled_spend' => 'object',
      'current_unpaid_unrepaid_invoice' => 'object',
      'custom_audience_info' => 'object',
      'customaudiences' => 'object',
      'customconversions' => 'object',
      'customer_po_number' => 'string',
      'daily_spend_limit' => 'object',
      'dcaf' => 'bool',
      'default_dsa_beneficiary' => 'string',
      'default_dsa_payor' => 'string',
      'default_unified_attribution_spec' => 'list<object>',
      'default_values' => 'object',
      'disable_reason' => 'int',
      'domain_and_site_links' => 'object',
      'dsa_recommendations' => 'object',
      'dynamic_probation_dsl' => 'float',
      'end_advertiser' => 'int',
      'end_advertiser_name' => 'string',
      'existing_customers' => 'list<string>',
      'expired_funding_source_details' => 'object',
      'extended_credit' => 'object',
      'extended_credit_info' => 'object',
      'extended_credit_invoice_group' => 'object',
      'failed_delivery_checks' => 'list<object>',
      'fb_entity' => 'int',
      'flex_single_objective' => 'FlexSingleObjective',
      'funding_source' => 'int',
      'funding_source_details' => 'object',
      'generatepreviews' => 'object',
      'has_active_skan_campaign_groups' => 'bool',
      'has_combo_cards_on_file' => 'bool',
      'has_extended_credit' => 'bool',
      'has_migrated_permissions' => 'bool',
      'has_page_authorized_adaccount' => 'bool',
      'has_personal_access' => 'bool',
      'has_purchase_optimization_eligible_page' => 'bool',
      'has_repay_processing_invoices' => 'bool',
      'has_started_purchase_optimized_ctm_ad_within_1d' => 'bool',
      'has_value_rule_set' => 'bool',
      'id' => 'string',
      'if_viewer_has_permission_to_advertise' => 'bool',
      'incremental_conversion_optimization_ad_studies' => 'list<object>',
      'instagram_accounts' => 'object',
      'invoicing_emails' => 'object',
      'ios_fourteen_campaign_limits' => 'object',
      'is_attribution_spec_system_default' => 'bool',
      'is_ba_skip_delayed_eligible' => 'bool',
      'is_biz_migration_eligible' => 'bool',
      'is_br_entity_account' => 'bool',
      'is_business_allowed_to_advertise' => 'bool',
      'is_business_verification_eligible' => 'bool',
      'is_closed_by_advertiser_compromise_bot' => 'bool',
      'is_collaborative_ads_ad_account' => 'bool',
      'is_ctx_advertiser' => 'bool',
      'is_direct_deals_enabled' => 'bool',
      'is_disabled_umbrella' => 'bool',
      'is_eligible_for_advantage_plus_creative_regulated_category' => 'bool',
      'is_expanded_shopless_awpt_eligible' => 'bool',
      'is_in_3ds_authorization_enabled_market' => 'bool',
      'is_mi_billing_info_updated' => 'bool',
      'is_mm_lite_api_enabled' => 'bool',
      'is_new_advertiser' => 'bool',
      'is_notifications_enabled' => 'bool',
      'is_oba_opt_out' => 'bool',
      'is_omnichannel_campaign_eligible' => 'bool',
      'is_pageless_ctwa_eligible' => 'bool',
      'is_pending_numbers_exposure_flag_enabled' => 'bool',
      'is_personal' => 'int',
      'is_pinless_debit_eligible' => 'bool',
      'is_placement_soft_opt_out_enabled' => 'bool',
      'is_prepay_account' => 'bool',
      'is_retail_media_network' => 'bool',
      'is_shopless_awpt_eligible' => 'bool',
      'is_tax_id_required' => 'bool',
      'is_tier_0' => 'bool',
      'is_tier_0_full' => 'bool',
      'is_tier_1' => 'bool',
      'is_tier_restricted' => 'bool',
      'is_update_timezone_currency_too_recently' => 'bool',
      'is_user_allowed_to_advertise' => 'bool',
      'is_using_higher_daily_flex_rate' => 'bool',
      'is_value_rules_smart_default_on' => 'bool',
      'is_wa_cloud_api_user' => 'bool',
      'is_youth_ads_pao_basic_advertiser' => 'bool',
      'is_youth_ads_pao_basic_advertiser_announcement_eligible' => 'bool',
      'last_spend_time' => 'int',
      'last_used_time' => 'int',
      'liable_address' => 'object',
      'liable_addresses' => 'object',
      'live_video_advertiser_details' => 'object',
      'marketing_message_enablement_status' => 'MarketingMessageEnablementStatus',
      'marketing_messages_settings' => 'object',
      'max_bid' => 'object',
      'max_billing_threshold' => 'object',
      'maybe_pac_internal_post_from_primary_post' => 'string',
      'media_agency' => 'int',
      'min_billing_threshold' => 'object',
      'min_campaign_group_spend_cap' => 'string',
      'min_daily_budget' => 'int',
      'min_live_boosting_budget' => 'int',
      'min_payment' => 'object',
      'minimum_budgets' => 'object',
      'modeled_reporting_type' => 'ModeledReportingType',
      'moo_default_conversion_bid' => 'int',
      'name' => 'string',
      'next_bill_date' => 'int',
      'offsite_pixels_tos_accepted' => 'bool',
      'onbehalf_requests' => 'object',
      'opportunity_score' => 'float',
      'opportunity_score_weight' => 'int',
      'owner' => 'string',
      'owner_business' => 'object',
      'page_authorized_country_for_political_ads' => 'list<object>',
      'pages_in_authorizations' => 'list<object>',
      'partner' => 'int',
      'payment_options' => 'object',
      'pending_billing_date_preference' => 'object',
      'prepay_account_balance' => 'object',
      'promotion_metadata' => 'list<object>',
      'promotion_metadata_live_crawl' => 'list<object>',
      'publisher_block_lists' => 'object',
      'reachestimate' => 'object',
      'reachfrequencypredictions' => 'object',
      'recommendations' => 'object',
      'rf_spec' => 'object',
      'sales_segment_v2' => 'string',
      'saved_audiences' => 'object',
      'segment' => 'Segment',
      'send_bill_to_address' => 'object',
      'send_bill_to_addresses' => 'object',
      'show_improved_boleto' => 'bool',
      'show_sac_campaign_group_input' => 'bool',
      'site_links_live_crawl' => 'list<object>',
      'sold_to_address' => 'object',
      'sold_to_addresses' => 'object',
      'spend_cap' => 'string',
      'spend_cap_history' => 'list<object>',
      'spendlimits' => 'object',
      'stored_balance_status' => 'StoredBalanceStatus',
      'subscribed_apps' => 'object',
      'targetingbrowse' => 'object',
      'targetingsearch' => 'object',
      'targetingsuggestions' => 'object',
      'tax_country' => 'string',
      'tax_exempt' => 'bool',
      'tax_id' => 'string',
      'tax_id_status' => 'int',
      'tax_id_type' => 'string',
      'timezone_id' => 'int',
      'timezone_name' => 'string',
      'timezone_offset_hours_utc' => 'float',
      'tos_accepted' => 'map<int, int>',
      'total_prepay_balance' => 'object',
      'tracking' => 'object',
      'transactions' => 'object',
      'user_access_expire_time' => 'int',
      'user_role' => 'string',
      'user_settings' => 'object',
      'user_tasks' => 'list<string>',
      'user_tos_accepted' => 'map<int, int>',
      'users' => 'object',
      'value_rule_set' => 'object',
      'viewable_business' => 'object',
      'viewable_businesses' => 'list<object>',
    );
  }
}
