<?php
 /*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 * All rights reserved.
 *
 * This source code is licensed under the license found in the
 * LICENSE file in the root directory of this source tree.
 */

namespace FacebookAds\Object\Values;

use FacebookAds\Enum\AbstractEnum;

/**
 * This class is auto-generated.
 *
 * For any issues or feature requests related to this class, please let us know
 * on github and we'll fix in our codegen framework. We'll not be able to accept
 * pull request for this class.
 *
 * @method static AdAccountAdVolumeRecommendationTypeValues getInstance()
 */
class AdAccountAdVolumeRecommendationTypeValues extends AbstractEnum {

  const AB_TEST = 'AB_TEST';
  const ACCOUNT_SPEND_LIMIT = 'ACCOUNT_SPEND_LIMIT';
  const ACO_TOGGLE = 'ACO_TOGGLE';
  const ADS_REPORTING = 'ADS_REPORTING';
  const ADVANCED_CAMPAIGN_BUDGET = 'ADVANCED_CAMPAIGN_BUDGET';
  const ADVANTAGE_CUSTOM_AUDIENCE = 'ADVANTAGE_CUSTOM_AUDIENCE';
  const ADVANTAGE_CUSTOM_AUDIENCE_UPSELL = 'ADVANTAGE_CUSTOM_AUDIENCE_UPSELL';
  const ADVANTAGE_PLUS_AUDIENCE_FRICTION = 'ADVANTAGE_PLUS_AUDIENCE_FRICTION';
  const ADVANTAGE_PLUS_AUDIENCE_TOGGLE = 'ADVANTAGE_PLUS_AUDIENCE_TOGGLE';
  const ADVANTAGE_PLUS_CREATIVE = 'ADVANTAGE_PLUS_CREATIVE';
  const ADVANTAGE_PLUS_CREATIVE_CATALOG = 'ADVANTAGE_PLUS_CREATIVE_CATALOG';
  const ADVANTAGE_SHOPPING_CAMPAIGN = 'ADVANTAGE_SHOPPING_CAMPAIGN';
  const ADVANTAGE_SHOPPING_CAMPAIGN_FRAGMENTATION = 'ADVANTAGE_SHOPPING_CAMPAIGN_FRAGMENTATION';
  const AD_OBJECTIVE = 'AD_OBJECTIVE';
  const AEM_V2_INELIGIBLE = 'AEM_V2_INELIGIBLE';
  const AGGREGATED_BID_LIMITED = 'AGGREGATED_BID_LIMITED';
  const AGGREGATED_BUDGET_LIMITED = 'AGGREGATED_BUDGET_LIMITED';
  const AGGREGATED_COST_LIMITED = 'AGGREGATED_COST_LIMITED';
  const APP_AEM_V2_INSTALLATION_PROMOTION = 'APP_AEM_V2_INSTALLATION_PROMOTION';
  const ASC_BUDGET_OPTIMIZATION = 'ASC_BUDGET_OPTIMIZATION';
  const ASC_BUDGET_OPTIMIZATION_PFR = 'ASC_BUDGET_OPTIMIZATION_PFR';
  const ASPECT_RATIO = 'ASPECT_RATIO';
  const ATLEAST_6_PLACEMENTS = 'ATLEAST_6_PLACEMENTS';
  const AUCTION_OVERLAP = 'AUCTION_OVERLAP';
  const AUCTION_OVERLAP_CONSOLIDATION = 'AUCTION_OVERLAP_CONSOLIDATION';
  const AUDIENCE_EXPANSION = 'AUDIENCE_EXPANSION';
  const AUDIENCE_EXPANSION_RETARGETING = 'AUDIENCE_EXPANSION_RETARGETING';
  const AUDIENCE_LEARNING_LIMITED = 'AUDIENCE_LEARNING_LIMITED';
  const AUTOFLOW_OPT_IN = 'AUTOFLOW_OPT_IN';
  const AUTOFLOW_OPT_IN_FALLBACK_DUPLICATION_FLOW = 'AUTOFLOW_OPT_IN_FALLBACK_DUPLICATION_FLOW';
  const AUTOMATIC_PLACEMENTS = 'AUTOMATIC_PLACEMENTS';
  const AUTO_BID = 'AUTO_BID';
  const BROAD_TARGETING = 'BROAD_TARGETING';
  const CAPI = 'CAPI';
  const CAPI_PERFORMANCE_MATCH_KEY = 'CAPI_PERFORMANCE_MATCH_KEY';
  const CASH_REWARDS_OPT_IN = 'CASH_REWARDS_OPT_IN';
  const CONNECT_FACEBOOK_PAGE_TO_INSTAGRAM = 'CONNECT_FACEBOOK_PAGE_TO_INSTAGRAM';
  const CONNECT_FACEBOOK_PAGE_TO_WHATSAPP = 'CONNECT_FACEBOOK_PAGE_TO_WHATSAPP';
  const COST_GOAL = 'COST_GOAL';
  const COST_GOAL_BUDGET_LIMITED = 'COST_GOAL_BUDGET_LIMITED';
  const COST_GOAL_CPA_LIMITED = 'COST_GOAL_CPA_LIMITED';
  const COST_PER_RESULT = 'COST_PER_RESULT';
  const CREATION_PACKAGE_UPGRADE_TO_ASC = 'CREATION_PACKAGE_UPGRADE_TO_ASC';
  const CREATION_PACKAGE_UPGRADE_TO_TLA = 'CREATION_PACKAGE_UPGRADE_TO_TLA';
  const CREATIVE_BADGE = 'CREATIVE_BADGE';
  const CREATIVE_DIVERSITY = 'CREATIVE_DIVERSITY';
  const CREATIVE_FATIGUE = 'CREATIVE_FATIGUE';
  const CREATIVE_FATIGUE_HOURLY = 'CREATIVE_FATIGUE_HOURLY';
  const CREATIVE_LIMITED = 'CREATIVE_LIMITED';
  const CREATIVE_LIMITED_HOURLY = 'CREATIVE_LIMITED_HOURLY';
  const CREATOR_ADS_PA_CONVERSION = 'CREATOR_ADS_PA_CONVERSION';
  const CTA = 'CTA';
  const DA_ADVANTAGE_PLUS_CREATIVE_INFO_LABELS = 'DA_ADVANTAGE_PLUS_CREATIVE_INFO_LABELS';
  const DEAD_LINK = 'DEAD_LINK';
  const DYNAMIC_ADVANTAGE_CAMPAIGN_BUDGET = 'DYNAMIC_ADVANTAGE_CAMPAIGN_BUDGET';
  const ECOSYSTEM_BID_REDUCE_L1_CARDINALITY = 'ECOSYSTEM_BID_REDUCE_L1_CARDINALITY';
  const FRAGMENTATION = 'FRAGMENTATION';
  const GES_TEST = 'GES_TEST';
  const GUIDANCE_CENTER_CODE_GEN = 'GUIDANCE_CENTER_CODE_GEN';
  const HIGH_COST = 'HIGH_COST';
  const HISTORICAL_BENCHMARK = 'HISTORICAL_BENCHMARK';
  const LEARNING_LIMITED = 'LEARNING_LIMITED';
  const LEARNING_PAUSE_FRICTION = 'LEARNING_PAUSE_FRICTION';
  const LEARNING_PHASE_BUDGET_EDITS = 'LEARNING_PHASE_BUDGET_EDITS';
  const LOW_OUTCOME = 'LOW_OUTCOME';
  const MERLIN_GUIDANCE = 'MERLIN_GUIDANCE';
  const MIXED_PA_COMBINE_ADSETS = 'MIXED_PA_COMBINE_ADSETS';
  const MMT_CAROUSEL_TO_VIDEO = 'MMT_CAROUSEL_TO_VIDEO';
  const MOBILE_FIRST_VIDEO = 'MOBILE_FIRST_VIDEO';
  const MR_AEMV2SUB_KCONSOLIDATION = 'MR_AEMV2SUB_KCONSOLIDATION';
  const MULTI_TEXT = 'MULTI_TEXT';
  const MUSIC = 'MUSIC';
  const NOT_APPLICABLE = 'NOT_APPLICABLE';
  const OPTIMAL_BAU = 'OPTIMAL_BAU';
  const PAYMENT_METHOD = 'PAYMENT_METHOD';
  const PERFORMANT_CREATIVE_REELS_OPT_IN = 'PERFORMANT_CREATIVE_REELS_OPT_IN';
  const PFR_L1_INLINE_MMT = 'PFR_L1_INLINE_MMT';
  const PREDICTIVE_CREATIVE_LIMITED = 'PREDICTIVE_CREATIVE_LIMITED';
  const PREDICTIVE_CREATIVE_LIMITED_HOURLY = 'PREDICTIVE_CREATIVE_LIMITED_HOURLY';
  const RAPID_LEARNING_LIMITED = 'RAPID_LEARNING_LIMITED';
  const RAPID_LEARNING_PHASE = 'RAPID_LEARNING_PHASE';
  const REELS_DUPLICATION_UPSELL = 'REELS_DUPLICATION_UPSELL';
  const REVERT = 'REVERT';
  const SCALE_GOOD_CAMPAIGN = 'SCALE_GOOD_CAMPAIGN';
  const SEMANTIC_BASED_AUDIENCE_EXPANSION = 'SEMANTIC_BASED_AUDIENCE_EXPANSION';
  const SETUP_PIXEL = 'SETUP_PIXEL';
  const SHOPS_ADS = 'SHOPS_ADS';
  const SIGNALS_GROWTH_CAPI = 'SIGNALS_GROWTH_CAPI';
  const SIGNALS_GROWTH_CAPI_TABLE = 'SIGNALS_GROWTH_CAPI_TABLE';
  const SIX_PLUS_MANUAL_PLACEMENTS = 'SIX_PLUS_MANUAL_PLACEMENTS';
  const SPEND_LIMIT = 'SPEND_LIMIT';
  const SYD_TEST_MODE = 'SYD_TEST_MODE';
  const TOP_ADSETS_WITH_ADS_UNDER_CAP = 'TOP_ADSETS_WITH_ADS_UNDER_CAP';
  const TOP_CAMPAIGNS_WITH_ADS_UNDER_CAP = 'TOP_CAMPAIGNS_WITH_ADS_UNDER_CAP';
  const TWO_P_GUIDANCE_CARD_AAA = 'TWO_P_GUIDANCE_CARD_AAA';
  const TWO_P_GUIDANCE_CARD_AUTO_PLACEMENT = 'TWO_P_GUIDANCE_CARD_AUTO_PLACEMENT';
  const TWO_P_GUIDANCE_CARD_CBO_OFF = 'TWO_P_GUIDANCE_CARD_CBO_OFF';
  const TWO_P_GUIDANCE_CARD_CTM_PREFLIGHT = 'TWO_P_GUIDANCE_CARD_CTM_PREFLIGHT';
  const UNCROP_IMAGE = 'UNCROP_IMAGE';
  const UNECONOMICAL_ADS_THROTTLING = 'UNECONOMICAL_ADS_THROTTLING';
  const UNUSED_BUDGET = 'UNUSED_BUDGET';
  const VIDEO_LENGTH = 'VIDEO_LENGTH';
  const ZERO_CONVERSION = 'ZERO_CONVERSION';
  const ZERO_IMPRESSION = 'ZERO_IMPRESSION';
}
