<?php
 /*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 * All rights reserved.
 *
 * This source code is licensed under the license found in the
 * LICENSE file in the root directory of this source tree.
 */

namespace FacebookAds\Object\Values;

use FacebookAds\Enum\AbstractEnum;

/**
 * This class is auto-generated.
 *
 * For any issues or feature requests related to this class, please let us know
 * on github and we'll fix in our codegen framework. We'll not be able to accept
 * pull request for this class.
 *
 * @method static AdPreviewAdFormatValues getInstance()
 */
class AdPreviewAdFormatValues extends AbstractEnum {

  const AUDIENCE_NETWORK_INSTREAM_VIDEO = 'AUDIENCE_NETWORK_INSTREAM_VIDEO';
  const AUDIENCE_NETWORK_INSTREAM_VIDEO_MOBILE = 'AUDIENCE_NETWORK_INSTREAM_VIDEO_MOBILE';
  const AUDIENCE_NETWORK_OUTSTREAM_VIDEO = 'AUDIENCE_NETWORK_OUTSTREAM_VIDEO';
  const AUDIENCE_NETWORK_REWARDED_VIDEO = 'AUDIENCE_NETWORK_REWARDED_VIDEO';
  const BIZ_DISCO_FEED_MOBILE = 'BIZ_DISCO_FEED_MOBILE';
  const DESKTOP_FEED_STANDARD = 'DESKTOP_FEED_STANDARD';
  const FACEBOOK_PROFILE_FEED_DESKTOP = 'FACEBOOK_PROFILE_FEED_DESKTOP';
  const FACEBOOK_PROFILE_FEED_MOBILE = 'FACEBOOK_PROFILE_FEED_MOBILE';
  const FACEBOOK_REELS_BANNER = 'FACEBOOK_REELS_BANNER';
  const FACEBOOK_REELS_BANNER_DESKTOP = 'FACEBOOK_REELS_BANNER_DESKTOP';
  const FACEBOOK_REELS_MOBILE = 'FACEBOOK_REELS_MOBILE';
  const FACEBOOK_REELS_POSTLOOP = 'FACEBOOK_REELS_POSTLOOP';
  const FACEBOOK_REELS_STICKER = 'FACEBOOK_REELS_STICKER';
  const FACEBOOK_STORY_MOBILE = 'FACEBOOK_STORY_MOBILE';
  const FACEBOOK_STORY_STICKER_MOBILE = 'FACEBOOK_STORY_STICKER_MOBILE';
  const INSTAGRAM_EXPLORE_CONTEXTUAL = 'INSTAGRAM_EXPLORE_CONTEXTUAL';
  const INSTAGRAM_EXPLORE_GRID_HOME = 'INSTAGRAM_EXPLORE_GRID_HOME';
  const INSTAGRAM_EXPLORE_IMMERSIVE = 'INSTAGRAM_EXPLORE_IMMERSIVE';
  const INSTAGRAM_FEED_WEB = 'INSTAGRAM_FEED_WEB';
  const INSTAGRAM_FEED_WEB_M_SITE = 'INSTAGRAM_FEED_WEB_M_SITE';
  const INSTAGRAM_PROFILE_FEED = 'INSTAGRAM_PROFILE_FEED';
  const INSTAGRAM_PROFILE_REELS = 'INSTAGRAM_PROFILE_REELS';
  const INSTAGRAM_REELS = 'INSTAGRAM_REELS';
  const INSTAGRAM_REELS_OVERLAY = 'INSTAGRAM_REELS_OVERLAY';
  const INSTAGRAM_SEARCH_CHAIN = 'INSTAGRAM_SEARCH_CHAIN';
  const INSTAGRAM_SEARCH_GRID = 'INSTAGRAM_SEARCH_GRID';
  const INSTAGRAM_STANDARD = 'INSTAGRAM_STANDARD';
  const INSTAGRAM_STORY = 'INSTAGRAM_STORY';
  const INSTAGRAM_STORY_EFFECT_TRAY = 'INSTAGRAM_STORY_EFFECT_TRAY';
  const INSTAGRAM_STORY_WEB = 'INSTAGRAM_STORY_WEB';
  const INSTAGRAM_STORY_WEB_M_SITE = 'INSTAGRAM_STORY_WEB_M_SITE';
  const INSTANT_ARTICLE_RECIRCULATION_AD = 'INSTANT_ARTICLE_RECIRCULATION_AD';
  const INSTANT_ARTICLE_STANDARD = 'INSTANT_ARTICLE_STANDARD';
  const INSTREAM_BANNER_DESKTOP = 'INSTREAM_BANNER_DESKTOP';
  const INSTREAM_BANNER_MOBILE = 'INSTREAM_BANNER_MOBILE';
  const INSTREAM_VIDEO_DESKTOP = 'INSTREAM_VIDEO_DESKTOP';
  const INSTREAM_VIDEO_IMAGE = 'INSTREAM_VIDEO_IMAGE';
  const INSTREAM_VIDEO_MOBILE = 'INSTREAM_VIDEO_MOBILE';
  const JOB_BROWSER_DESKTOP = 'JOB_BROWSER_DESKTOP';
  const JOB_BROWSER_MOBILE = 'JOB_BROWSER_MOBILE';
  const MARKETPLACE_MOBILE = 'MARKETPLACE_MOBILE';
  const MESSENGER_MOBILE_INBOX_MEDIA = 'MESSENGER_MOBILE_INBOX_MEDIA';
  const MESSENGER_MOBILE_STORY_MEDIA = 'MESSENGER_MOBILE_STORY_MEDIA';
  const MOBILE_BANNER = 'MOBILE_BANNER';
  const MOBILE_FEED_BASIC = 'MOBILE_FEED_BASIC';
  const MOBILE_FEED_STANDARD = 'MOBILE_FEED_STANDARD';
  const MOBILE_FULLWIDTH = 'MOBILE_FULLWIDTH';
  const MOBILE_INTERSTITIAL = 'MOBILE_INTERSTITIAL';
  const MOBILE_MEDIUM_RECTANGLE = 'MOBILE_MEDIUM_RECTANGLE';
  const MOBILE_NATIVE = 'MOBILE_NATIVE';
  const RIGHT_COLUMN_STANDARD = 'RIGHT_COLUMN_STANDARD';
  const SUGGESTED_VIDEO_DESKTOP = 'SUGGESTED_VIDEO_DESKTOP';
  const SUGGESTED_VIDEO_MOBILE = 'SUGGESTED_VIDEO_MOBILE';
  const WATCH_FEED_HOME = 'WATCH_FEED_HOME';
  const WATCH_FEED_MOBILE = 'WATCH_FEED_MOBILE';
}
