<?php
/**
 * Copyright (c) 2015-present, Facebook, Inc. All rights reserved.
 *
 * You are hereby granted a non-exclusive, worldwide, royalty-free license to
 * use, copy, modify, and distribute this software in source code or binary
 * form for use in connection with the web services and APIs provided by
 * Facebook.
 *
 * As with any software that integrates with the Facebook platform, your use
 * of this software is subject to the Facebook Developer Principles and
 * Policies [http://developers.facebook.com/policy/]. This copyright notice
 * shall be included in all copies or substantial portions of the software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

namespace FacebookAds\Object\Values;

use FacebookAds\Enum\AbstractEnum;

/**
 * This class is auto-generated.
 *
 * For any issues or feature requests related to this class, please let us know
 * on github and we'll fix in our codegen framework. We'll not be able to accept
 * pull request for this class.
 *
 * @method static AdPreviewAdFormatValues getInstance()
 */
class AdPreviewAdFormatValues extends AbstractEnum {

  const AUDIENCE_NETWORK_INSTREAM_VIDEO = 'AUDIENCE_NETWORK_INSTREAM_VIDEO';
  const AUDIENCE_NETWORK_INSTREAM_VIDEO_MOBILE = 'AUDIENCE_NETWORK_INSTREAM_VIDEO_MOBILE';
  const AUDIENCE_NETWORK_OUTSTREAM_VIDEO = 'AUDIENCE_NETWORK_OUTSTREAM_VIDEO';
  const AUDIENCE_NETWORK_REWARDED_VIDEO = 'AUDIENCE_NETWORK_REWARDED_VIDEO';
  const DESKTOP_FEED_STANDARD = 'DESKTOP_FEED_STANDARD';
  const FACEBOOK_STORY_MOBILE = 'FACEBOOK_STORY_MOBILE';
  const INSTAGRAM_EXPLORE_CONTEXTUAL = 'INSTAGRAM_EXPLORE_CONTEXTUAL';
  const INSTAGRAM_EXPLORE_IMMERSIVE = 'INSTAGRAM_EXPLORE_IMMERSIVE';
  const INSTAGRAM_REELS = 'INSTAGRAM_REELS';
  const INSTAGRAM_STANDARD = 'INSTAGRAM_STANDARD';
  const INSTAGRAM_STORY = 'INSTAGRAM_STORY';
  const INSTANT_ARTICLE_RECIRCULATION_AD = 'INSTANT_ARTICLE_RECIRCULATION_AD';
  const INSTANT_ARTICLE_STANDARD = 'INSTANT_ARTICLE_STANDARD';
  const INSTREAM_BANNER_DESKTOP = 'INSTREAM_BANNER_DESKTOP';
  const INSTREAM_BANNER_MOBILE = 'INSTREAM_BANNER_MOBILE';
  const INSTREAM_VIDEO_DESKTOP = 'INSTREAM_VIDEO_DESKTOP';
  const INSTREAM_VIDEO_IMAGE = 'INSTREAM_VIDEO_IMAGE';
  const INSTREAM_VIDEO_MOBILE = 'INSTREAM_VIDEO_MOBILE';
  const JOB_BROWSER_DESKTOP = 'JOB_BROWSER_DESKTOP';
  const JOB_BROWSER_MOBILE = 'JOB_BROWSER_MOBILE';
  const MARKETPLACE_MOBILE = 'MARKETPLACE_MOBILE';
  const MESSENGER_MOBILE_INBOX_MEDIA = 'MESSENGER_MOBILE_INBOX_MEDIA';
  const MESSENGER_MOBILE_STORY_MEDIA = 'MESSENGER_MOBILE_STORY_MEDIA';
  const MOBILE_BANNER = 'MOBILE_BANNER';
  const MOBILE_FEED_BASIC = 'MOBILE_FEED_BASIC';
  const MOBILE_FEED_STANDARD = 'MOBILE_FEED_STANDARD';
  const MOBILE_FULLWIDTH = 'MOBILE_FULLWIDTH';
  const MOBILE_INTERSTITIAL = 'MOBILE_INTERSTITIAL';
  const MOBILE_MEDIUM_RECTANGLE = 'MOBILE_MEDIUM_RECTANGLE';
  const MOBILE_NATIVE = 'MOBILE_NATIVE';
  const RIGHT_COLUMN_STANDARD = 'RIGHT_COLUMN_STANDARD';
  const SUGGESTED_VIDEO_DESKTOP = 'SUGGESTED_VIDEO_DESKTOP';
  const SUGGESTED_VIDEO_MOBILE = 'SUGGESTED_VIDEO_MOBILE';
  const WATCH_FEED_HOME = 'WATCH_FEED_HOME';
  const WATCH_FEED_MOBILE = 'WATCH_FEED_MOBILE';
}
