<?php
 /*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 * All rights reserved.
 *
 * This source code is licensed under the license found in the
 * LICENSE file in the root directory of this source tree.
 */

namespace FacebookAds\Object\Values;

use FacebookAds\Enum\AbstractEnum;

/**
 * This class is auto-generated.
 *
 * For any issues or feature requests related to this class, please let us know
 * on github and we'll fix in our codegen framework. We'll not be able to accept
 * pull request for this class.
 *
 * @method static AdRuleUiCreationSourceValues getInstance()
 */
class AdRuleUiCreationSourceValues extends AbstractEnum {

  const AM_ACCOUNT_OVERVIEW_RECOMMENDATIONS = 'AM_ACCOUNT_OVERVIEW_RECOMMENDATIONS';
  const AM_ACTIVITY_HISTORY_TABLE = 'AM_ACTIVITY_HISTORY_TABLE';
  const AM_AD_OBJECT_NAME_CARD = 'AM_AD_OBJECT_NAME_CARD';
  const AM_AMFE_L3_RECOMMENDATION = 'AM_AMFE_L3_RECOMMENDATION';
  const AM_AUTOFLOW_GUIDANCE_CARD = 'AM_AUTOFLOW_GUIDANCE_CARD';
  const AM_AUTO_APPLY_WIDGET = 'AM_AUTO_APPLY_WIDGET';
  const AM_EDITOR_CARD = 'AM_EDITOR_CARD';
  const AM_INFO_CARD = 'AM_INFO_CARD';
  const AM_NAME_CELL_DROPDOWN = 'AM_NAME_CELL_DROPDOWN';
  const AM_OPTIMIZATION_TIP_GUIDANCE_CARD = 'AM_OPTIMIZATION_TIP_GUIDANCE_CARD';
  const AM_PERFORMANCE_SUMMARY = 'AM_PERFORMANCE_SUMMARY';
  const AM_RULE_LANDING_PAGE_BANNER = 'AM_RULE_LANDING_PAGE_BANNER';
  const AM_SYD_RESOLUTION_FLOW = 'AM_SYD_RESOLUTION_FLOW';
  const AM_SYD_RESOLUTION_FLOW_MODAL = 'AM_SYD_RESOLUTION_FLOW_MODAL';
  const AM_TABLE_DELIVERY_COLUMN_POPOVER = 'AM_TABLE_DELIVERY_COLUMN_POPOVER';
  const AM_TABLE_TOGGLE_POPOVER = 'AM_TABLE_TOGGLE_POPOVER';
  const AM_TOOLBAR_CREATE_RULE_DROPDOWN = 'AM_TOOLBAR_CREATE_RULE_DROPDOWN';
  const PE_CAMPAIGN_STRUCTURE_MENU = 'PE_CAMPAIGN_STRUCTURE_MENU';
  const PE_EDITOR_CARD = 'PE_EDITOR_CARD';
  const PE_INFO_CARD = 'PE_INFO_CARD';
  const PE_TOOLBAR_CREATE_RULE_DROPDOWN = 'PE_TOOLBAR_CREATE_RULE_DROPDOWN';
  const RULES_MANAGEMENT_PAGE_ACTION_DROPDOWN = 'RULES_MANAGEMENT_PAGE_ACTION_DROPDOWN';
  const RULES_MANAGEMENT_PAGE_RULE_GROUP = 'RULES_MANAGEMENT_PAGE_RULE_GROUP';
  const RULES_MANAGEMENT_PAGE_RULE_NAME = 'RULES_MANAGEMENT_PAGE_RULE_NAME';
  const RULES_MANAGEMENT_PAGE_TOP_NAV = 'RULES_MANAGEMENT_PAGE_TOP_NAV';
  const RULES_VIEW_ACTIVE_RULES_DIALOG = 'RULES_VIEW_ACTIVE_RULES_DIALOG';
  const RULE_CREATION_SUCCESS_DIALOG = 'RULE_CREATION_SUCCESS_DIALOG';
  const RULE_SYD_REDIRECT = 'RULE_SYD_REDIRECT';
  const RULE_TEMPLATES_DIALOG = 'RULE_TEMPLATES_DIALOG';
}
