<?php
/**
 * Copyright (c) 2015-present, Facebook, Inc. All rights reserved.
 *
 * You are hereby granted a non-exclusive, worldwide, royalty-free license to
 * use, copy, modify, and distribute this software in source code or binary
 * form for use in connection with the web services and APIs provided by
 * Facebook.
 *
 * As with any software that integrates with the Facebook platform, your use
 * of this software is subject to the Facebook Developer Principles and
 * Policies [http://developers.facebook.com/policy/]. This copyright notice
 * shall be included in all copies or substantial portions of the software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

namespace FacebookAds\Object\Values;

use FacebookAds\Enum\AbstractEnum;

/**
 * This class is auto-generated.
 *
 * For any issues or feature requests related to this class, please let us know
 * on github and we'll fix in our codegen framework. We'll not be able to accept
 * pull request for this class.
 *
 * @method static AdVideoContainerTypeValues getInstance()
 */
class AdVideoContainerTypeValues extends AbstractEnum {

  const LEGACY = 'LEGACY';
  const CONTAINED_POST_ATTACHMENT = 'CONTAINED_POST_ATTACHMENT';
  const SAY_THANKS_DEPRECATED = 'SAY_THANKS_DEPRECATED';
  const LOOK_NOW_DEPRECATED = 'LOOK_NOW_DEPRECATED';
  const BROADCAST = 'BROADCAST';
  const ALBUM_MULTIMEDIA_POST = 'ALBUM_MULTIMEDIA_POST';
  const UNLISTED = 'UNLISTED';
  const NO_STORY = 'NO_STORY';
  const GOODWILL_ANNIVERSARY_DEPRECATED = 'GOODWILL_ANNIVERSARY_DEPRECATED';
  const PROFILE_VIDEO = 'PROFILE_VIDEO';
  const DIRECT_INBOX = 'DIRECT_INBOX';
  const DIRECT_INBOX_REACTION = 'DIRECT_INBOX_REACTION';
  const STORYLINE = 'STORYLINE';
  const GROUP_POST = 'GROUP_POST';
  const ATLAS_VIDEO = 'ATLAS_VIDEO';
  const LIVE_PHOTO = 'LIVE_PHOTO';
  const TEMP_MULTIMEDIA_POST = 'TEMP_MULTIMEDIA_POST';
  const GOODWILL_ANNIVERSARY_PROMOTION_DEPRECATED = 'GOODWILL_ANNIVERSARY_PROMOTION_DEPRECATED';
  const GOODWILL_VIDEO_SHARE = 'GOODWILL_VIDEO_SHARE';
  const GOODWILL_VIDEO_PROMOTION = 'GOODWILL_VIDEO_PROMOTION';
  const COPYRIGHT_REFERENCE_VIDEO = 'COPYRIGHT_REFERENCE_VIDEO';
  const CANVAS = 'CANVAS';
  const MOMENTS_VIDEO = 'MOMENTS_VIDEO';
  const APP_REVIEW_SCREENCAST = 'APP_REVIEW_SCREENCAST';
  const VIDEO_COMMENT = 'VIDEO_COMMENT';
  const COPYRIGHT_REFERENCE_BROADCAST = 'COPYRIGHT_REFERENCE_BROADCAST';
  const OFFERS_VIDEO = 'OFFERS_VIDEO';
  const JOB_APPLICATION_VIDEO = 'JOB_APPLICATION_VIDEO';
  const STORYLINE_WITH_EXTERNAL_MUSIC = 'STORYLINE_WITH_EXTERNAL_MUSIC';
  const JOB_OPENING_VIDEO = 'JOB_OPENING_VIDEO';
  const PAGE_SLIDESHOW_VIDEO = 'PAGE_SLIDESHOW_VIDEO';
  const INSTANT_ARTICLE = 'INSTANT_ARTICLE';
  const PRODUCT_VIDEO = 'PRODUCT_VIDEO';
  const DIRECTED_POST_ATTACHMENT = 'DIRECTED_POST_ATTACHMENT';
  const PROFILE_INTRO_CARD = 'PROFILE_INTRO_CARD';
  const ISSUE_MODULE = 'ISSUE_MODULE';
  const GOODWILL_VIDEO_TOKEN_REQUIRED = 'GOODWILL_VIDEO_TOKEN_REQUIRED';
  const INSTANT_APPLICATION_PREVIEW = 'INSTANT_APPLICATION_PREVIEW';
  const REPLACE_VIDEO = 'REPLACE_VIDEO';
  const FACECAST_DVR = 'FACECAST_DVR';
  const PIXELCLOUD = 'PIXELCLOUD';
  const SLIDESHOW_SHAKR = 'SLIDESHOW_SHAKR';
  const INSPIRATION_VIDEO = 'INSPIRATION_VIDEO';
  const TAROT_DIGEST = 'TAROT_DIGEST';
  const SLIDESHOW_ANIMOTO = 'SLIDESHOW_ANIMOTO';
  const AUDIO_BROADCAST = 'AUDIO_BROADCAST';
  const LEARN = 'LEARN';
  const CULTURAL_MOMENT_DEPRECATED = 'CULTURAL_MOMENT_DEPRECATED';
  const YOUR_DAY = 'YOUR_DAY';
  const PAGES_COVER_VIDEO = 'PAGES_COVER_VIDEO';
  const GOODWILL_VIDEO_CONTAINED_SHARE = 'GOODWILL_VIDEO_CONTAINED_SHARE';
  const DCO_AD_ASSET_FEED = 'DCO_AD_ASSET_FEED';
  const CONTAINED_POST_BROADCAST = 'CONTAINED_POST_BROADCAST';
  const QUICK_PROMOTION = 'QUICK_PROMOTION';
  const DYNAMIC_ITEM_DISPLAY_BUNDLE = 'DYNAMIC_ITEM_DISPLAY_BUNDLE';
  const EVENT_TOUR = 'EVENT_TOUR';
  const EVENT_COVER_VIDEO = 'EVENT_COVER_VIDEO';
  const AD_DERIVATIVE = 'AD_DERIVATIVE';
  const CONTAINED_POST_AUDIO_BROADCAST = 'CONTAINED_POST_AUDIO_BROADCAST';
  const LIVE_CREATIVE_KIT_VIDEO = 'LIVE_CREATIVE_KIT_VIDEO';
  const ALOHA_SUPERFRAME = 'ALOHA_SUPERFRAME';
  const INSTAGRAM_VIDEO_COPY = 'INSTAGRAM_VIDEO_COPY';
  const AD_BREAK_PREVIEW = 'AD_BREAK_PREVIEW';
  const ALOHA_CALL_VIDEO = 'ALOHA_CALL_VIDEO';
  const STORY_ARCHIVE_VIDEO = 'STORY_ARCHIVE_VIDEO';
  const BRAND_EQUITY_POLL_VIDEO = 'BRAND_EQUITY_POLL_VIDEO';
  const PROFILE_COVER_VIDEO = 'PROFILE_COVER_VIDEO';
  const DYNAMIC_ITEM_VIDEO = 'DYNAMIC_ITEM_VIDEO';
  const PAGE_REVIEW_SCREENCAST = 'PAGE_REVIEW_SCREENCAST';
  const HEURISTIC_PREVIEW = 'HEURISTIC_PREVIEW';
  const GAME_CLIP = 'GAME_CLIP';
  const WOODHENGE = 'WOODHENGE';
  const PREMIERE_SOURCE = 'PREMIERE_SOURCE';
  const PRIVATE_GALLERY_VIDEO = 'PRIVATE_GALLERY_VIDEO';
  const FISTBUMP = 'FISTBUMP';
  const STORY_HIGHLIGHT_VIDEO = 'STORY_HIGHLIGHT_VIDEO';
  const PROFILE_TO_PAGE_UPLOADED_VIDEO = 'PROFILE_TO_PAGE_UPLOADED_VIDEO';
  const KOTOTORO = 'KOTOTORO';
  const DYNAMIC_TEMPLATE_VIDEO = 'DYNAMIC_TEMPLATE_VIDEO';
  const INSTANT_GAME_CLIP = 'INSTANT_GAME_CLIP';
  const CANDIDATE_VIDEOS = 'CANDIDATE_VIDEOS';
  const FUNDRAISER_COVER_VIDEO = 'FUNDRAISER_COVER_VIDEO';
  const PROTON = 'PROTON';
  const BELL_POLL = 'BELL_POLL';
  const CIVIC_PROPOSAL_COVER_VIDEO = 'CIVIC_PROPOSAL_COVER_VIDEO';
}
