<?php
/**
 * Copyright (c) 2015-present, Facebook, Inc. All rights reserved.
 *
 * You are hereby granted a non-exclusive, worldwide, royalty-free license to
 * use, copy, modify, and distribute this software in source code or binary
 * form for use in connection with the web services and APIs provided by
 * Facebook.
 *
 * As with any software that integrates with the Facebook platform, your use
 * of this software is subject to the Facebook Developer Principles and
 * Policies [http://developers.facebook.com/policy/]. This copyright notice
 * shall be included in all copies or substantial portions of the software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

namespace FacebookAds\Object\Values;

use FacebookAds\Enum\AbstractEnum;

/**
 * This class is auto-generated.
 *
 * For any issues or feature requests related to this class, please let us know
 * on github and we'll fix in our codegen framework. We'll not be able to accept
 * pull request for this class.
 *
 * @method static AdVideoContainerTypeValues getInstance()
 */
class AdVideoContainerTypeValues extends AbstractEnum {

  const ACO_AUTOEXTRACTED_VIDEO = 'ACO_AUTOEXTRACTED_VIDEO';
  const ACO_VIDEO_VARIATION = 'ACO_VIDEO_VARIATION';
  const ADS_AI_GENERATED = 'ADS_AI_GENERATED';
  const AD_BREAK_PREVIEW = 'AD_BREAK_PREVIEW';
  const AD_DERIVATIVE = 'AD_DERIVATIVE';
  const AD_LIBRARY_WATERMARK = 'AD_LIBRARY_WATERMARK';
  const AGE_UP = 'AGE_UP';
  const ALBUM_MULTIMEDIA_POST = 'ALBUM_MULTIMEDIA_POST';
  const ALOHA_CALL_VIDEO = 'ALOHA_CALL_VIDEO';
  const ALOHA_SUPERFRAME = 'ALOHA_SUPERFRAME';
  const APP_REREVIEW_SCREENCAST = 'APP_REREVIEW_SCREENCAST';
  const APP_REVIEW_SCREENCAST = 'APP_REVIEW_SCREENCAST';
  const ASSET_MANAGER = 'ASSET_MANAGER';
  const ATLAS_VIDEO = 'ATLAS_VIDEO';
  const AUDIO_BRIEF = 'AUDIO_BRIEF';
  const AUDIO_BROADCAST = 'AUDIO_BROADCAST';
  const AUDIO_COMMENT = 'AUDIO_COMMENT';
  const BROADCAST = 'BROADCAST';
  const BULLETIN_ARTICLE_AUDIO = 'BULLETIN_ARTICLE_AUDIO';
  const CANDIDATE_VIDEOS_DELETED = 'CANDIDATE_VIDEOS_DELETED';
  const CANVAS = 'CANVAS';
  const CFC_VIDEO = 'CFC_VIDEO';
  const CMS_MEDIA_MANAGER = 'CMS_MEDIA_MANAGER';
  const CONTAINED_POST_ATTACHMENT = 'CONTAINED_POST_ATTACHMENT';
  const CONTAINED_POST_AUDIO_BROADCAST = 'CONTAINED_POST_AUDIO_BROADCAST';
  const CONTAINED_POST_COPYRIGHT_REFERENCE_BROADCAST = 'CONTAINED_POST_COPYRIGHT_REFERENCE_BROADCAST';
  const COPYRIGHT_REFERENCE_BROADCAST = 'COPYRIGHT_REFERENCE_BROADCAST';
  const COPYRIGHT_REFERENCE_VIDEO = 'COPYRIGHT_REFERENCE_VIDEO';
  const CREATION_ML_PRECREATION = 'CREATION_ML_PRECREATION';
  const DCO_AD_ASSET_FEED = 'DCO_AD_ASSET_FEED';
  const DCO_AUTOGEN_VIDEO = 'DCO_AUTOGEN_VIDEO';
  const DCO_TRIMMED_VIDEO = 'DCO_TRIMMED_VIDEO';
  const DIM_SUM = 'DIM_SUM';
  const DIRECTED_POST_ATTACHMENT = 'DIRECTED_POST_ATTACHMENT';
  const DIRECT_INBOX = 'DIRECT_INBOX';
  const DIRECT_INBOX_REACTION = 'DIRECT_INBOX_REACTION';
  const DROPS_SHOPPING_EVENT_PAGE = 'DROPS_SHOPPING_EVENT_PAGE';
  const DYNAMIC_ITEM_DISPLAY_BUNDLE = 'DYNAMIC_ITEM_DISPLAY_BUNDLE';
  const DYNAMIC_ITEM_VIDEO = 'DYNAMIC_ITEM_VIDEO';
  const DYNAMIC_TEMPLATE_VIDEO = 'DYNAMIC_TEMPLATE_VIDEO';
  const EVENT_COVER_VIDEO = 'EVENT_COVER_VIDEO';
  const EVENT_TOUR = 'EVENT_TOUR';
  const FACECAST_DVR = 'FACECAST_DVR';
  const FB_AVATAR_ANIMATED_SATP = 'FB_AVATAR_ANIMATED_SATP';
  const FB_COLLECTIBLE_VIDEO = 'FB_COLLECTIBLE_VIDEO';
  const FB_SHORTS = 'FB_SHORTS';
  const FB_SHORTS_CONTENT_REMIXABLE = 'FB_SHORTS_CONTENT_REMIXABLE';
  const FB_SHORTS_CROSS_META_POST = 'FB_SHORTS_CROSS_META_POST';
  const FB_SHORTS_GROUP_POST = 'FB_SHORTS_GROUP_POST';
  const FB_SHORTS_PMV_POST = 'FB_SHORTS_PMV_POST';
  const FB_SHORTS_PMV_POST_NO_NEWSFEED_NOR_TIMELINE = 'FB_SHORTS_PMV_POST_NO_NEWSFEED_NOR_TIMELINE';
  const FB_SHORTS_POST = 'FB_SHORTS_POST';
  const FB_SHORTS_REMIX_POST = 'FB_SHORTS_REMIX_POST';
  const FUNDRAISER_COVER_VIDEO = 'FUNDRAISER_COVER_VIDEO';
  const GAME_CLIP = 'GAME_CLIP';
  const GEMSTONE = 'GEMSTONE';
  const GIF_TO_VIDEO = 'GIF_TO_VIDEO';
  const GOODWILL_ANNIVERSARY_DEPRECATED = 'GOODWILL_ANNIVERSARY_DEPRECATED';
  const GOODWILL_ANNIVERSARY_PROMOTION_DEPRECATED = 'GOODWILL_ANNIVERSARY_PROMOTION_DEPRECATED';
  const GOODWILL_VIDEO_CONTAINED_SHARE = 'GOODWILL_VIDEO_CONTAINED_SHARE';
  const GOODWILL_VIDEO_PROMOTION = 'GOODWILL_VIDEO_PROMOTION';
  const GOODWILL_VIDEO_SHARE = 'GOODWILL_VIDEO_SHARE';
  const GOODWILL_VIDEO_TOKEN_REQUIRED = 'GOODWILL_VIDEO_TOKEN_REQUIRED';
  const GROUP_POST = 'GROUP_POST';
  const HACK_TV = 'HACK_TV';
  const HEURISTIC_CLUSTER_VIDEO = 'HEURISTIC_CLUSTER_VIDEO';
  const HEURISTIC_PREVIEW = 'HEURISTIC_PREVIEW';
  const HIGHLIGHT_CLIP_VIDEO = 'HIGHLIGHT_CLIP_VIDEO';
  const HUDDLE_BROADCAST = 'HUDDLE_BROADCAST';
  const IG_REELS_XPV = 'IG_REELS_XPV';
  const IG_STORIES_READER = 'IG_STORIES_READER';
  const INJECTABLE = 'INJECTABLE';
  const INSPIRATION_VIDEO = 'INSPIRATION_VIDEO';
  const INSTAGRAM_VIDEO_COPY = 'INSTAGRAM_VIDEO_COPY';
  const INSTANT_APPLICATION_PREVIEW = 'INSTANT_APPLICATION_PREVIEW';
  const INSTANT_ARTICLE = 'INSTANT_ARTICLE';
  const INSTANT_GAME_CLIP = 'INSTANT_GAME_CLIP';
  const ISSUE_MODULE = 'ISSUE_MODULE';
  const JOBS_CAREERS = 'JOBS_CAREERS';
  const JOBS_VISUAL_INTRO_ENTRY = 'JOBS_VISUAL_INTRO_ENTRY';
  const JOB_APPLICATION_VIDEO = 'JOB_APPLICATION_VIDEO';
  const JOB_OPENING_VIDEO = 'JOB_OPENING_VIDEO';
  const KOTOTORO = 'KOTOTORO';
  const LEARN = 'LEARN';
  const LEGACY = 'LEGACY';
  const LEGACY_CONTAINED_POST_BROADCAST = 'LEGACY_CONTAINED_POST_BROADCAST';
  const LIVE_AUDIO_ROOM_BROADCAST = 'LIVE_AUDIO_ROOM_BROADCAST';
  const LIVE_CLIP_PREVIEW = 'LIVE_CLIP_PREVIEW';
  const LIVE_CLIP_WORKCHAT = 'LIVE_CLIP_WORKCHAT';
  const LIVE_CREATIVE_KIT_VIDEO = 'LIVE_CREATIVE_KIT_VIDEO';
  const LIVE_PHOTO = 'LIVE_PHOTO';
  const LOOK_NOW_DEPRECATED = 'LOOK_NOW_DEPRECATED';
  const MARKETPLACE_LISTING_VIDEO = 'MARKETPLACE_LISTING_VIDEO';
  const MARKETPLACE_PRE_RECORDED_VIDEO = 'MARKETPLACE_PRE_RECORDED_VIDEO';
  const MESSENGER_WATCH_TOGETHER = 'MESSENGER_WATCH_TOGETHER';
  const MOMENTS_VIDEO = 'MOMENTS_VIDEO';
  const MUSIC_CLIP = 'MUSIC_CLIP';
  const MUSIC_CLIP_IN_AUDIO_DIGEST = 'MUSIC_CLIP_IN_AUDIO_DIGEST';
  const MUSIC_CLIP_IN_COMMENT = 'MUSIC_CLIP_IN_COMMENT';
  const MUSIC_CLIP_IN_LIGHTWEIGHT_STATUS = 'MUSIC_CLIP_IN_LIGHTWEIGHT_STATUS';
  const MUSIC_CLIP_IN_POLL_OPTION = 'MUSIC_CLIP_IN_POLL_OPTION';
  const MUSIC_CLIP_ON_DATING_PROFILE = 'MUSIC_CLIP_ON_DATING_PROFILE';
  const NEO_ASYNC_GAME_VIDEO = 'NEO_ASYNC_GAME_VIDEO';
  const NEW_CONTAINED_POST_BROADCAST = 'NEW_CONTAINED_POST_BROADCAST';
  const NO_STORY = 'NO_STORY';
  const NO_STORY_WITH_ENTPOST = 'NO_STORY_WITH_ENTPOST';
  const NPE_COLLAB_COPYRIGHT_CHECK = 'NPE_COLLAB_COPYRIGHT_CHECK';
  const OCULUS_CREATOR_PORTAL = 'OCULUS_CREATOR_PORTAL';
  const OCULUS_VENUES_BROADCAST = 'OCULUS_VENUES_BROADCAST';
  const OFFERS_VIDEO = 'OFFERS_VIDEO';
  const PAGES_COVER_VIDEO = 'PAGES_COVER_VIDEO';
  const PAGE_REVIEW_SCREENCAST = 'PAGE_REVIEW_SCREENCAST';
  const PAGE_SLIDESHOW_VIDEO = 'PAGE_SLIDESHOW_VIDEO';
  const PAID_CONTENT_PREVIEW = 'PAID_CONTENT_PREVIEW';
  const PAID_CONTENT_VIDEO = 'PAID_CONTENT_VIDEO';
  const PAID_CONTENT_VIDEO__POST = 'PAID_CONTENT_VIDEO__POST';
  const PAPER_DOCUMENT_AUDIO = 'PAPER_DOCUMENT_AUDIO';
  const PAPER_DOCUMENT_VIDEO = 'PAPER_DOCUMENT_VIDEO';
  const PIXELCLOUD = 'PIXELCLOUD';
  const PODCAST_HIGHLIGHT = 'PODCAST_HIGHLIGHT';
  const PODCAST_ML_PREVIEW = 'PODCAST_ML_PREVIEW';
  const PODCAST_ML_PREVIEW_NO_NEWSFEED_STORY = 'PODCAST_ML_PREVIEW_NO_NEWSFEED_STORY';
  const PODCAST_RSS = 'PODCAST_RSS';
  const PODCAST_RSS_EPHEMERAL = 'PODCAST_RSS_EPHEMERAL';
  const PODCAST_RSS_NO_NEWSFEED_STORY = 'PODCAST_RSS_NO_NEWSFEED_STORY';
  const PODCAST_VOICES = 'PODCAST_VOICES';
  const PODCAST_VOICES_NO_NEWSFEED_STORY = 'PODCAST_VOICES_NO_NEWSFEED_STORY';
  const PREMIERE_SOURCE = 'PREMIERE_SOURCE';
  const PREMIUM_MUSIC_VIDEO_CLIP = 'PREMIUM_MUSIC_VIDEO_CLIP';
  const PREMIUM_MUSIC_VIDEO_CROPPED_CLIP = 'PREMIUM_MUSIC_VIDEO_CROPPED_CLIP';
  const PREMIUM_MUSIC_VIDEO_NO_NEWSFEED_STORY = 'PREMIUM_MUSIC_VIDEO_NO_NEWSFEED_STORY';
  const PREMIUM_MUSIC_VIDEO_WITH_NEWSFEED_STORY = 'PREMIUM_MUSIC_VIDEO_WITH_NEWSFEED_STORY';
  const PRIVATE_GALLERY_VIDEO = 'PRIVATE_GALLERY_VIDEO';
  const PRODUCT_VIDEO = 'PRODUCT_VIDEO';
  const PROFILE_COVER_VIDEO = 'PROFILE_COVER_VIDEO';
  const PROFILE_INTRO_CARD = 'PROFILE_INTRO_CARD';
  const PROFILE_VIDEO = 'PROFILE_VIDEO';
  const PROTON = 'PROTON';
  const QUICK_PROMOTION = 'QUICK_PROMOTION';
  const REPLACE_VIDEO = 'REPLACE_VIDEO';
  const SALES_CLIENT_INTERACTION = 'SALES_CLIENT_INTERACTION';
  const SAY_THANKS_DEPRECATED = 'SAY_THANKS_DEPRECATED';
  const SHOWREEL_NATIVE_DUMMY_VIDEO = 'SHOWREEL_NATIVE_DUMMY_VIDEO';
  const SLIDESHOW_ANIMOTO = 'SLIDESHOW_ANIMOTO';
  const SLIDESHOW_SHAKR = 'SLIDESHOW_SHAKR';
  const SLIDESHOW_VARIATION_VIDEO = 'SLIDESHOW_VARIATION_VIDEO';
  const SOTTO_CONTENT = 'SOTTO_CONTENT';
  const SOUNDBITES_VIDEO = 'SOUNDBITES_VIDEO';
  const SOUND_PLATFORM_STREAM = 'SOUND_PLATFORM_STREAM';
  const SRT_ATTACHMENT = 'SRT_ATTACHMENT';
  const STAGES_BROADCAST = 'STAGES_BROADCAST';
  const STORIES_VIDEO = 'STORIES_VIDEO';
  const STORIES_WEARABLE = 'STORIES_WEARABLE';
  const STORYLINE = 'STORYLINE';
  const STORYLINE_WITH_EXTERNAL_MUSIC = 'STORYLINE_WITH_EXTERNAL_MUSIC';
  const STORY_ARCHIVE_VIDEO = 'STORY_ARCHIVE_VIDEO';
  const STORY_CARD_TEMPLATE = 'STORY_CARD_TEMPLATE';
  const STREAM_HIGHLIGHTS_VIDEO = 'STREAM_HIGHLIGHTS_VIDEO';
  const TAROT_DIGEST = 'TAROT_DIGEST';
  const TEMPORARY_UNLISTED = 'TEMPORARY_UNLISTED';
  const TEMP_MULTIMEDIA_POST = 'TEMP_MULTIMEDIA_POST';
  const UNLISTED = 'UNLISTED';
  const UNLISTED_HACK_TV = 'UNLISTED_HACK_TV';
  const UNLISTED_HORIZON = 'UNLISTED_HORIZON';
  const UNLISTED_OCULUS = 'UNLISTED_OCULUS';
  const VIDEO_COMMENT = 'VIDEO_COMMENT';
  const VIDEO_COMPOSITION_VARIATION = 'VIDEO_COMPOSITION_VARIATION';
  const VIDEO_CREATIVE_EDITOR_AUTOGEN_AD_VIDEO = 'VIDEO_CREATIVE_EDITOR_AUTOGEN_AD_VIDEO';
  const VIDEO_SUPERRES = 'VIDEO_SUPERRES';
  const VOICES_ARTICLE_VIDEO = 'VOICES_ARTICLE_VIDEO';
  const VU_GENERATED_VIDEO = 'VU_GENERATED_VIDEO';
  const WOODHENGE = 'WOODHENGE';
  const WORK_KNOWLEDGE_VIDEO = 'WORK_KNOWLEDGE_VIDEO';
  const YOUR_DAY = 'YOUR_DAY';
}
