<?php
/**
 * Copyright (c) 2015-present, Facebook, Inc. All rights reserved.
 *
 * You are hereby granted a non-exclusive, worldwide, royalty-free license to
 * use, copy, modify, and distribute this software in source code or binary
 * form for use in connection with the web services and APIs provided by
 * Facebook.
 *
 * As with any software that integrates with the Facebook platform, your use
 * of this software is subject to the Facebook Developer Principles and
 * Policies [http://developers.facebook.com/policy/]. This copyright notice
 * shall be included in all copies or substantial portions of the software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

namespace FacebookAds\Object\Values;

use FacebookAds\Enum\AbstractEnum;

/**
 * This class is auto-generated.
 *
 * For any issues or feature requests related to this class, please let us know
 * on github and we'll fix in our codegen framework. We'll not be able to accept
 * pull request for this class.
 *
 * @method static BusinessSubverticalV2Values getInstance()
 */
class BusinessSubverticalV2Values extends AbstractEnum {

  const ACCOUNTING_AND_TAX = 'ACCOUNTING_AND_TAX';
  const ACTIVITIES_AND_LEISURE = 'ACTIVITIES_AND_LEISURE';
  const AIR = 'AIR';
  const APPAREL_AND_ACCESSORIES = 'APPAREL_AND_ACCESSORIES';
  const ARTS_AND_HERITAGE_AND_EDUCATION = 'ARTS_AND_HERITAGE_AND_EDUCATION';
  const AR_OR_VR_GAMING = 'AR_OR_VR_GAMING';
  const AUDIO_STREAMING = 'AUDIO_STREAMING';
  const AUTO = 'AUTO';
  const AUTO_INSURANCE = 'AUTO_INSURANCE';
  const AUTO_RENTAL = 'AUTO_RENTAL';
  const BABY = 'BABY';
  const BALLOT_INITIATIVE_OR_REFERENDUM = 'BALLOT_INITIATIVE_OR_REFERENDUM';
  const BEAUTY = 'BEAUTY';
  const BEAUTY_AND_FASHION = 'BEAUTY_AND_FASHION';
  const BEER_AND_WINE_AND_LIQUOR_AND_MALT_BEVERAGES = 'BEER_AND_WINE_AND_LIQUOR_AND_MALT_BEVERAGES';
  const BOOKSTORES = 'BOOKSTORES';
  const BROADCAST_TELEVISION = 'BROADCAST_TELEVISION';
  const BUSINESS_CONSULTANTS = 'BUSINESS_CONSULTANTS';
  const BUYING_AGENCY = 'BUYING_AGENCY';
  const CABLE_AND_SATELLITE = 'CABLE_AND_SATELLITE';
  const CABLE_TELEVISION = 'CABLE_TELEVISION';
  const CALL_CENTER_AND_MESSAGING_SERVICES = 'CALL_CENTER_AND_MESSAGING_SERVICES';
  const CANDIDATE_OR_POLITICIAN = 'CANDIDATE_OR_POLITICIAN';
  const CAREER = 'CAREER';
  const CAREER_AND_TECH = 'CAREER_AND_TECH';
  const CASUAL_DINING = 'CASUAL_DINING';
  const CHRONIC_CONDITIONS_AND_MEDICAL_CAUSES = 'CHRONIC_CONDITIONS_AND_MEDICAL_CAUSES';
  const CIVIC_INFLUENCERS = 'CIVIC_INFLUENCERS';
  const CLINICAL_TRIALS = 'CLINICAL_TRIALS';
  const COFFEE = 'COFFEE';
  const COMPUTER_AND_SOFTWARE_AND_HARDWARE = 'COMPUTER_AND_SOFTWARE_AND_HARDWARE';
  const CONSOLE_AND_CROSS_PLATFORM_GAMING = 'CONSOLE_AND_CROSS_PLATFORM_GAMING';
  const CONSULTING = 'CONSULTING';
  const CONSUMER_ELECTRONICS = 'CONSUMER_ELECTRONICS';
  const COUNSELING_AND_PSYCHOTHERAPY = 'COUNSELING_AND_PSYCHOTHERAPY';
  const CREATIVE_AGENCY = 'CREATIVE_AGENCY';
  const CREDIT_AND_FINANCING_AND_MORTAGES = 'CREDIT_AND_FINANCING_AND_MORTAGES';
  const CRUISES_AND_MARINE = 'CRUISES_AND_MARINE';
  const CULTURE_AND_LIFESTYLE = 'CULTURE_AND_LIFESTYLE';
  const DATA_ANALYTICS_AND_DATA_MANAGEMENT = 'DATA_ANALYTICS_AND_DATA_MANAGEMENT';
  const DATING_AND_TECHNOLOGY_APPS = 'DATING_AND_TECHNOLOGY_APPS';
  const DEPARTMENT_STORE = 'DEPARTMENT_STORE';
  const DESKTOP_SOFTWARE = 'DESKTOP_SOFTWARE';
  const DIETING_AND_FITNESS_PROGRAMS = 'DIETING_AND_FITNESS_PROGRAMS';
  const DIGITAL_NATIVE_EDUCATION_OR_TRAINING = 'DIGITAL_NATIVE_EDUCATION_OR_TRAINING';
  const DRINKING_PLACES = 'DRINKING_PLACES';
  const EDUCATION_RESOURCES = 'EDUCATION_RESOURCES';
  const ED_TECH = 'ED_TECH';
  const ELEARNING_AND_MASSIVE_ONLINE_OPEN_COURSES = 'ELEARNING_AND_MASSIVE_ONLINE_OPEN_COURSES';
  const ELECTION_COMMISSION = 'ELECTION_COMMISSION';
  const ELECTRONICS_AND_APPLIANCES = 'ELECTRONICS_AND_APPLIANCES';
  const ENGINEERING_AND_DESIGN = 'ENGINEERING_AND_DESIGN';
  const ENVIRONMENT_AND_ANIMAL_WELFARE = 'ENVIRONMENT_AND_ANIMAL_WELFARE';
  const ESPORTS = 'ESPORTS';
  const EVENTS = 'EVENTS';
  const FARMING_AND_RANCHING = 'FARMING_AND_RANCHING';
  const FILE_STORAGE_AND_CLOUD_AND_DATA_SERVICES = 'FILE_STORAGE_AND_CLOUD_AND_DATA_SERVICES';
  const FINANCE = 'FINANCE';
  const FIN_TECH = 'FIN_TECH';
  const FISHING_AND_HUNTING_AND_FORESTRY_AND_LOGGING = 'FISHING_AND_HUNTING_AND_FORESTRY_AND_LOGGING';
  const FITNESS = 'FITNESS';
  const FOOD = 'FOOD';
  const FOOTWEAR = 'FOOTWEAR';
  const FOR_PROFIT_COLLEGES_AND_UNIVERSITIES = 'FOR_PROFIT_COLLEGES_AND_UNIVERSITIES';
  const FULL_SERVICE_AGENCY = 'FULL_SERVICE_AGENCY';
  const GOVERNMENT_CONTROLLED_ENTITY = 'GOVERNMENT_CONTROLLED_ENTITY';
  const GOVERNMENT_DEPARTMENT_OR_AGENCY = 'GOVERNMENT_DEPARTMENT_OR_AGENCY';
  const GOVERNMENT_OFFICIAL = 'GOVERNMENT_OFFICIAL';
  const GOVERNMENT_OWNED_MEDIA = 'GOVERNMENT_OWNED_MEDIA';
  const GROCERY_AND_DRUG_AND_CONVENIENCE = 'GROCERY_AND_DRUG_AND_CONVENIENCE';
  const HEAD_OF_STATE = 'HEAD_OF_STATE';
  const HEALTH_INSURANCE = 'HEALTH_INSURANCE';
  const HEALTH_SYSTEMS_AND_PRACTITIONERS = 'HEALTH_SYSTEMS_AND_PRACTITIONERS';
  const HEALTH_TECH = 'HEALTH_TECH';
  const HOME_AND_FURNITURE_AND_OFFICE = 'HOME_AND_FURNITURE_AND_OFFICE';
  const HOME_IMPROVEMENT = 'HOME_IMPROVEMENT';
  const HOME_INSURANCE = 'HOME_INSURANCE';
  const HOME_TECH = 'HOME_TECH';
  const HOTEL_AND_ACCOMODATION = 'HOTEL_AND_ACCOMODATION';
  const HOUSEHOLD_GOODS_DURABLE = 'HOUSEHOLD_GOODS_DURABLE';
  const HOUSEHOLD_GOODS_NON_DURABLE = 'HOUSEHOLD_GOODS_NON_DURABLE';
  const HR_AND_FINANCIAL_MANAGEMENT = 'HR_AND_FINANCIAL_MANAGEMENT';
  const HUMANITARIAN_OR_DISASTER_RELIEF = 'HUMANITARIAN_OR_DISASTER_RELIEF';
  const INDEPENDENT_EXPENDITURE_GROUP = 'INDEPENDENT_EXPENDITURE_GROUP';
  const INSURANCE_TECH = 'INSURANCE_TECH';
  const INTERNATIONAL_ORGANIZATON = 'INTERNATIONAL_ORGANIZATON';
  const INVESTMENT_BANK_AND_BROKERAGE = 'INVESTMENT_BANK_AND_BROKERAGE';
  const ISSUE_ADVOCACY = 'ISSUE_ADVOCACY';
  const LEGAL = 'LEGAL';
  const LIFE_INSURANCE = 'LIFE_INSURANCE';
  const LOGISTICS_AND_TRANSPORTATION_AND_FLEET_MANAGEMENT = 'LOGISTICS_AND_TRANSPORTATION_AND_FLEET_MANAGEMENT';
  const MANUFACTURING = 'MANUFACTURING';
  const MEDICAL_DEVICES_AND_SUPPLIES_AND_EQUIPMENT = 'MEDICAL_DEVICES_AND_SUPPLIES_AND_EQUIPMENT';
  const MEDSPA_AND_ELECTIVE_SURGERIES_AND_ALTERNATIVE_MEDICINE = 'MEDSPA_AND_ELECTIVE_SURGERIES_AND_ALTERNATIVE_MEDICINE';
  const MINING_AND_QUARRYING = 'MINING_AND_QUARRYING';
  const MOBILE_GAMING = 'MOBILE_GAMING';
  const MOVIES = 'MOVIES';
  const MUSEUMS_AND_PARKS_AND_LIBRARIES = 'MUSEUMS_AND_PARKS_AND_LIBRARIES';
  const MUSIC = 'MUSIC';
  const NETWORK_SECURITY_PRODUCTS = 'NETWORK_SECURITY_PRODUCTS';
  const NEWS_AND_CURRENT_EVENTS = 'NEWS_AND_CURRENT_EVENTS';
  const NON_PRESCRIPTION = 'NON_PRESCRIPTION';
  const NOT_FOR_PROFIT_COLLEGES_AND_UNIVERSITIES = 'NOT_FOR_PROFIT_COLLEGES_AND_UNIVERSITIES';
  const OFFICE = 'OFFICE';
  const OFFICE_OR_BUSINESS_SUPPLIES = 'OFFICE_OR_BUSINESS_SUPPLIES';
  const OIL_AND_GAS_AND_CONSUMABLE_FUEL = 'OIL_AND_GAS_AND_CONSUMABLE_FUEL';
  const ONLINE_ONLY_PUBLICATIONS = 'ONLINE_ONLY_PUBLICATIONS';
  const PACKAGE_OR_FREIGHT_DELIVERY = 'PACKAGE_OR_FREIGHT_DELIVERY';
  const PARTY_INDEPENDENT_EXPENDITURE_GROUP_US = 'PARTY_INDEPENDENT_EXPENDITURE_GROUP_US';
  const PAYMENT_PROCESSING_AND_GATEWAY_SOLUTIONS = 'PAYMENT_PROCESSING_AND_GATEWAY_SOLUTIONS';
  const PC_GAMING = 'PC_GAMING';
  const PEOPLE = 'PEOPLE';
  const PERSONAL_CARE = 'PERSONAL_CARE';
  const PET = 'PET';
  const PHOTOGRAPHY_AND_FILMING_SERVICES = 'PHOTOGRAPHY_AND_FILMING_SERVICES';
  const PIZZA = 'PIZZA';
  const PLANNING_AGENCY = 'PLANNING_AGENCY';
  const POLITICAL_PARTY_OR_COMMITTEE = 'POLITICAL_PARTY_OR_COMMITTEE';
  const PRESCRIPTION = 'PRESCRIPTION';
  const PROFESSIONAL_ASSOCIATIONS = 'PROFESSIONAL_ASSOCIATIONS';
  const PROPERTY_AND_CASUALTY = 'PROPERTY_AND_CASUALTY';
  const QUICK_SERVICE = 'QUICK_SERVICE';
  const RADIO = 'RADIO';
  const RAILROADS = 'RAILROADS';
  const REAL_ESTATE = 'REAL_ESTATE';
  const REAL_MONEY_GAMING = 'REAL_MONEY_GAMING';
  const RECREATIONAL = 'RECREATIONAL';
  const RELIGIOUS = 'RELIGIOUS';
  const RESELLER = 'RESELLER';
  const RESIDENTIAL_AND_LONG_TERM_CARE_FACILITIES_AND_OUTPATIENT_CARE_CENTERS = 'RESIDENTIAL_AND_LONG_TERM_CARE_FACILITIES_AND_OUTPATIENT_CARE_CENTERS';
  const RETAIL_AND_CREDIT_UNION_AND_COMMERCIAL_BANK = 'RETAIL_AND_CREDIT_UNION_AND_COMMERCIAL_BANK';
  const RIDE_SHARING_OR_TAXI_SERVICES = 'RIDE_SHARING_OR_TAXI_SERVICES';
  const SAFETY_SERVICES = 'SAFETY_SERVICES';
  const SCHOLARLY = 'SCHOLARLY';
  const SCHOOL_AND_EARLY_CHILDREN_EDCATION = 'SCHOOL_AND_EARLY_CHILDREN_EDCATION';
  const SOCIAL_MEDIA = 'SOCIAL_MEDIA';
  const SOFTWARE_AS_A_SERVICE = 'SOFTWARE_AS_A_SERVICE';
  const SPORTING = 'SPORTING';
  const SPORTING_AND_OUTDOOR = 'SPORTING_AND_OUTDOOR';
  const SPORTS = 'SPORTS';
  const SUPERSTORES = 'SUPERSTORES';
  const T1_AUTOMOTIVE_MANUFACTURER = 'T1_AUTOMOTIVE_MANUFACTURER';
  const T1_MOTORCYCLE = 'T1_MOTORCYCLE';
  const T2_DEALER_ASSOCIATIONS = 'T2_DEALER_ASSOCIATIONS';
  const T3_AUTO_AGENCY = 'T3_AUTO_AGENCY';
  const T3_AUTO_RESELLERS = 'T3_AUTO_RESELLERS';
  const T3_DEALER_GROUPS = 'T3_DEALER_GROUPS';
  const T3_FRANCHISE_DEALER = 'T3_FRANCHISE_DEALER';
  const T3_INDEPENDENT_DEALER = 'T3_INDEPENDENT_DEALER';
  const T3_PARTS_AND_SERVICES = 'T3_PARTS_AND_SERVICES';
  const T3_PORTALS = 'T3_PORTALS';
  const TELECOMMUNICATIONS_EQUIPMENT_AND_ACCESSORIES = 'TELECOMMUNICATIONS_EQUIPMENT_AND_ACCESSORIES';
  const TELEPHONE_SERVICE_PROVIDERS_AND_CARRIERS = 'TELEPHONE_SERVICE_PROVIDERS_AND_CARRIERS';
  const TICKETING = 'TICKETING';
  const TOBACCO = 'TOBACCO';
  const TOURISM_AND_TRAVEL_SERVICES = 'TOURISM_AND_TRAVEL_SERVICES';
  const TOURISM_BOARD = 'TOURISM_BOARD';
  const TOY_AND_HOBBY = 'TOY_AND_HOBBY';
  const TRADE_SCHOOL = 'TRADE_SCHOOL';
  const TRAVEL_AGENCIES_AND_GUIDES_AND_OTAS = 'TRAVEL_AGENCIES_AND_GUIDES_AND_OTAS';
  const UTILITIES_AND_ENERGY_EQUIPMENT_AND_SERVICES = 'UTILITIES_AND_ENERGY_EQUIPMENT_AND_SERVICES';
  const VETERINARY_CLINICS_AND_SERVICES = 'VETERINARY_CLINICS_AND_SERVICES';
  const VIDEO_STREAMING = 'VIDEO_STREAMING';
  const VIRTUAL_SERVICES = 'VIRTUAL_SERVICES';
  const VITAMINS_OR_WELLNESS = 'VITAMINS_OR_WELLNESS';
  const WAREHOUSING_AND_STORAGE = 'WAREHOUSING_AND_STORAGE';
  const WATER_AND_SOFT_DRINK_AND_BAVERAGE = 'WATER_AND_SOFT_DRINK_AND_BAVERAGE';
  const WEBSITE_DESIGNERS_OR_GRAPHIC_DESIGNERS = 'WEBSITE_DESIGNERS_OR_GRAPHIC_DESIGNERS';
  const WHOLESALE = 'WHOLESALE';
  const WIRELESS_SERVICES = 'WIRELESS_SERVICES';
}
