<?php
/**
 * Copyright (c) 2015-present, Facebook, Inc. All rights reserved.
 *
 * You are hereby granted a non-exclusive, worldwide, royalty-free license to
 * use, copy, modify, and distribute this software in source code or binary
 * form for use in connection with the web services and APIs provided by
 * Facebook.
 *
 * As with any software that integrates with the Facebook platform, your use
 * of this software is subject to the Facebook Developer Principles and
 * Policies [http://developers.facebook.com/policy/]. This copyright notice
 * shall be included in all copies or substantial portions of the software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

namespace FacebookAds\Object\Values;

use FacebookAds\Enum\AbstractEnum;

/**
 * This class is auto-genereated.
 *
 * For any issues or feature requests related to this class, please let us know
 * on github and we'll fix in our codegen framework. We'll not be able to accept
 * pull request for this class.
 *
 * @method static ProductItemReviewRejectionReasonsValues getInstance()
 */
class ProductItemReviewRejectionReasonsValues extends AbstractEnum {

  const UNKNOWN = 'UNKNOWN';
  const IRREGULAR_APP_INSTALL = 'IRREGULAR_APP_INSTALL';
  const TEXT_OVERLAY = 'TEXT_OVERLAY';
  const ADULT_CONTENT = 'ADULT_CONTENT';
  const ADULT_HEALTH = 'ADULT_HEALTH';
  const ALCOHOL = 'ALCOHOL';
  const ANIMATED_IMAGE = 'ANIMATED_IMAGE';
  const BEFORE_AND_AFTER = 'BEFORE_AND_AFTER';
  const CASUAL_DATING = 'CASUAL_DATING';
  const DATING = 'DATING';
  const FACEBOOK_REFERENCE = 'FACEBOOK_REFERENCE';
  const FINANCIAL = 'FINANCIAL';
  const GAMBLING = 'GAMBLING';
  const IDEALIZED_BODY = 'IDEALIZED_BODY';
  const LANGUAGE = 'LANGUAGE';
  const LANDING_PAGE_FAIL = 'LANDING_PAGE_FAIL';
  const SEXUAL = 'SEXUAL';
  const TEST = 'TEST';
  const TOBACCO_SALE = 'TOBACCO_SALE';
  const TRAPPING = 'TRAPPING';
  const UNSUBSTANTIATED_CLAIM = 'UNSUBSTANTIATED_CLAIM';
  const OTHER = 'OTHER';
  const WEAPON_SALE = 'WEAPON_SALE';
  const WORK_FROM_HOME = 'WORK_FROM_HOME';
  const CASH_ADVANCE = 'CASH_ADVANCE';
  const SHOCK_AND_SCARE = 'SHOCK_AND_SCARE';
  const SPY_CAMERA = 'SPY_CAMERA';
  const BAD_HEALTH_PRODUCT = 'BAD_HEALTH_PRODUCT';
  const GRAMMAR = 'GRAMMAR';
  const ILLEGAL = 'ILLEGAL';
  const MISUSE_OF_LIKE = 'MISUSE_OF_LIKE';
  const NON_EXISTENT_FUNCTIONALITY = 'NON_EXISTENT_FUNCTIONALITY';
  const ONLINE_PHARMACY = 'ONLINE_PHARMACY';
  const PENNY_AUCTION = 'PENNY_AUCTION';
  const PORN = 'PORN';
  const COPYRIGHT = 'COPYRIGHT';
  const TRADEMARK = 'TRADEMARK';
  const COUNTERFEIT = 'COUNTERFEIT';
  const SYSTEM_ISSUE = 'SYSTEM_ISSUE';
  const Q_BLURRY_PIXELATED = 'Q_BLURRY_PIXELATED';
  const Q_BORDERLINE_SEXUAL = 'Q_BORDERLINE_SEXUAL';
  const Q_BORDER_BACKGROUND = 'Q_BORDER_BACKGROUND';
  const Q_GRAMMAR_CAPITALIZATION = 'Q_GRAMMAR_CAPITALIZATION';
  const Q_IRRELEVANT_IMAGE_COPY = 'Q_IRRELEVANT_IMAGE_COPY';
  const Q_MISLEADING = 'Q_MISLEADING';
  const Q_MULTIPLE_IMAGES = 'Q_MULTIPLE_IMAGES';
  const Q_HOT_BUTTON = 'Q_HOT_BUTTON';
  const Q_ZOOM_IN_BODY_PARTS = 'Q_ZOOM_IN_BODY_PARTS';
  const Q_ZOOM_IN_FOOD = 'Q_ZOOM_IN_FOOD';
  const QUALITY_LOW = 'QUALITY_LOW';
  const LEAD_AD_FROM_AGGREGATOR = 'LEAD_AD_FROM_AGGREGATOR';
  const UNSUITABLE_QUESTION = 'UNSUITABLE_QUESTION';
  const FRAUD_ASSOCIATED = 'FRAUD_ASSOCIATED';
  const MYSTERY_IMAGE = 'MYSTERY_IMAGE';
  const APP_SCAM = 'APP_SCAM';
  const TEXT_PENALTY_HIGH = 'TEXT_PENALTY_HIGH';
  const TEXT_PENALTY_MEDIUM = 'TEXT_PENALTY_MEDIUM';
  const TEXT_PENALTY_LOW = 'TEXT_PENALTY_LOW';
  const BAD_SUBSCRIPTION = 'BAD_SUBSCRIPTION';
  const FACEBOOK_WORD_MANIPULATED = 'FACEBOOK_WORD_MANIPULATED';
  const FACEBOOK_ICONS = 'FACEBOOK_ICONS';
  const FACEBOOK_PAGE_LOOKALIKE = 'FACEBOOK_PAGE_LOOKALIKE';
  const FACEBOOK_LOGO_FOCUS = 'FACEBOOK_LOGO_FOCUS';
  const FACEBOOK_LOGO_OVERLAP = 'FACEBOOK_LOGO_OVERLAP';
  const FACEBOOK_LOGO = 'FACEBOOK_LOGO';
  const FACEBOOK_LOGO_THUMBS_UP = 'FACEBOOK_LOGO_THUMBS_UP';
  const FACEBOOK_SCREENSHOT_PROD = 'FACEBOOK_SCREENSHOT_PROD';
  const FACEBOOK_WORDMARK = 'FACEBOOK_WORDMARK';
  const FACEBOOK_ZUCKPIC = 'FACEBOOK_ZUCKPIC';
  const HIGHLIGHTED_PAIN_POINTS = 'HIGHLIGHTED_PAIN_POINTS';
  const PERFECT_BODY = 'PERFECT_BODY';
  const SCALES = 'SCALES';
  const TAPE_MEASURE = 'TAPE_MEASURE';
  const UNDESIRABLE_BODY = 'UNDESIRABLE_BODY';
  const ZOOM_BODY_PART = 'ZOOM_BODY_PART';
  const HARRASSMENT = 'HARRASSMENT';
  const USER_ATTRIBUTES_CALLOUT = 'USER_ATTRIBUTES_CALLOUT';
  const USER_FINANICAL_CALLOUT = 'USER_FINANICAL_CALLOUT';
  const USER_HEALTH_ATTRIBUTES = 'USER_HEALTH_ATTRIBUTES';
  const USER_WEIGHT_ATTRIBUTES = 'USER_WEIGHT_ATTRIBUTES';
  const PROFANITY = 'PROFANITY';
  const FAKE_FORM_ELEMENTS = 'FAKE_FORM_ELEMENTS';
  const FAKE_NOTIFICATIONS = 'FAKE_NOTIFICATIONS';
  const MOUSE_CURSOR = 'MOUSE_CURSOR';
  const PLAY_BUTTON = 'PLAY_BUTTON';
  const QR_CODES = 'QR_CODES';
  const EXCESSIVE_SKIN = 'EXCESSIVE_SKIN';
  const INDIRECT_NUDITY = 'INDIRECT_NUDITY';
  const INDIRECT_SEXUAL_ACT = 'INDIRECT_SEXUAL_ACT';
  const SEXUAL_OTHER = 'SEXUAL_OTHER';
  const ZOOM_SEXUAL_IMAGE = 'ZOOM_SEXUAL_IMAGE';
  const BREASTENLARGEMENT = 'BREASTENLARGEMENT';
  const GENITALSURGERY = 'GENITALSURGERY';
  const LIBIDO = 'LIBIDO';
  const NUDITY_NOTPORN = 'NUDITY_NOTPORN';
  const PHEROMONE = 'PHEROMONE';
  const SCHEME_HOTGIRLPAGE = 'SCHEME_HOTGIRLPAGE';
  const SERVICES_SEDUCTION = 'SERVICES_SEDUCTION';
  const SEXPUBLICATIONS = 'SEXPUBLICATIONS';
  const SEXTOYS = 'SEXTOYS';
  const SEXUALPLEASURE = 'SEXUALPLEASURE';
  const STRIPCLUBS = 'STRIPCLUBS';
  const MENTION_BOTOX = 'MENTION_BOTOX';
  const MENTION_DIETPRODUCT = 'MENTION_DIETPRODUCT';
  const MENTION_LASERS = 'MENTION_LASERS';
  const MENTION_SEXUALHEALTH = 'MENTION_SEXUALHEALTH';
  const MENTION_SUPPLEMENT = 'MENTION_SUPPLEMENT';
  const MENTION_SURGERY = 'MENTION_SURGERY';
  const MENTION_BRAND_ALCOHOL = 'MENTION_BRAND_ALCOHOL';
  const MENTION_CONSUMPTION_ALCOHOL = 'MENTION_CONSUMPTION_ALCOHOL';
  const MENTION_SALES_ALCOHOL = 'MENTION_SALES_ALCOHOL';
  const SPONSORSHIP = 'SPONSORSHIP';
  const MENTION_SALES_BADHEALTHPRODUCT = 'MENTION_SALES_BADHEALTHPRODUCT';
  const UNCLEAR_CANCELLATION_SUBSCRIPTION = 'UNCLEAR_CANCELLATION_SUBSCRIPTION';
  const UNCLEAR_PRICING_SUBSCRIPTION = 'UNCLEAR_PRICING_SUBSCRIPTION';
  const BA_HAIRLOSS = 'BA_HAIRLOSS';
  const BA_MEDICAL = 'BA_MEDICAL';
  const BA_SKIN = 'BA_SKIN';
  const BA_TEETH = 'BA_TEETH';
  const BA_WEIGHTLOSS = 'BA_WEIGHTLOSS';
  const GIBBERISH = 'GIBBERISH';
  const RANDOMCHARACTERS = 'RANDOMCHARACTERS';
  const DRUGS_ILLEGAL = 'DRUGS_ILLEGAL';
  const HUMAN_TRAFFICKING = 'HUMAN_TRAFFICKING';
  const SERVICES_ESCORT = 'SERVICES_ESCORT';
  const IMAGE_ANIMALCRUELTY = 'IMAGE_ANIMALCRUELTY';
  const IMAGE_MEDICAL = 'IMAGE_MEDICAL';
  const IMAGE_OFFENSIVEGESTURE = 'IMAGE_OFFENSIVEGESTURE';
  const IMAGE_VEHICLECOLLISION = 'IMAGE_VEHICLECOLLISION';
  const IMAGE_WEAPONATUSER = 'IMAGE_WEAPONATUSER';
  const MENTION_IMAGE_VIOLENCE_GORE = 'MENTION_IMAGE_VIOLENCE_GORE';
  const MENTION_ACCESSORY_CONSUMPTION_TOBACCO = 'MENTION_ACCESSORY_CONSUMPTION_TOBACCO';
  const MENTION_BRAND_TOBACCO = 'MENTION_BRAND_TOBACCO';
  const FALSENOTIFICATION = 'FALSENOTIFICATION';
  const IMPOSSIBLECURES = 'IMPOSSIBLECURES';
  const MENTION_NUMERIC_CLAIM = 'MENTION_NUMERIC_CLAIM';
  const MENTION_TRICKSTIPS = 'MENTION_TRICKSTIPS';
  const SPECIFICINDIVIDUALCLAIM = 'SPECIFICINDIVIDUALCLAIM';
  const UNREALISTIC_EBOOKPROMISE = 'UNREALISTIC_EBOOKPROMISE';
  const VIDEOSEXUAL = 'VIDEOSEXUAL';
  const VIDEOSCHOCKANDSCARE = 'VIDEOSCHOCKANDSCARE';
  const VIDEOLANGUAGE = 'VIDEOLANGUAGE';
  const NOT_DATING_PARTNER = 'NOT_DATING_PARTNER';
}
