<?php
 /*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 * All rights reserved.
 *
 * This source code is licensed under the license found in the
 * LICENSE file in the root directory of this source tree.
 */

namespace FacebookAds\Object\Values;

use FacebookAds\Enum\AbstractEnum;

/**
 * This class is auto-generated.
 *
 * For any issues or feature requests related to this class, please let us know
 * on github and we'll fix in our codegen framework. We'll not be able to accept
 * pull request for this class.
 *
 * @method static ProductItemCommerceTaxCategoryValues getInstance()
 */
class ProductItemCommerceTaxCategoryValues extends AbstractEnum {

  const FB_ANIMAL = 'FB_ANIMAL';
  const FB_ANIMAL_SUPP = 'FB_ANIMAL_SUPP';
  const FB_APRL = 'FB_APRL';
  const FB_APRL_ACCESSORIES = 'FB_APRL_ACCESSORIES';
  const FB_APRL_ATHL_UNIF = 'FB_APRL_ATHL_UNIF';
  const FB_APRL_CASES = 'FB_APRL_CASES';
  const FB_APRL_CLOTHING = 'FB_APRL_CLOTHING';
  const FB_APRL_COSTUME = 'FB_APRL_COSTUME';
  const FB_APRL_CSTM = 'FB_APRL_CSTM';
  const FB_APRL_FORMAL = 'FB_APRL_FORMAL';
  const FB_APRL_HANDBAG = 'FB_APRL_HANDBAG';
  const FB_APRL_JEWELRY = 'FB_APRL_JEWELRY';
  const FB_APRL_SHOE = 'FB_APRL_SHOE';
  const FB_APRL_SHOE_ACC = 'FB_APRL_SHOE_ACC';
  const FB_APRL_SWIM = 'FB_APRL_SWIM';
  const FB_APRL_SWIM_CHIL = 'FB_APRL_SWIM_CHIL';
  const FB_APRL_SWIM_CVR = 'FB_APRL_SWIM_CVR';
  const FB_ARTS = 'FB_ARTS';
  const FB_ARTS_HOBBY = 'FB_ARTS_HOBBY';
  const FB_ARTS_PARTY = 'FB_ARTS_PARTY';
  const FB_ARTS_PARTY_GIFT_CARD = 'FB_ARTS_PARTY_GIFT_CARD';
  const FB_ARTS_TICKET = 'FB_ARTS_TICKET';
  const FB_BABY = 'FB_BABY';
  const FB_BABY_BATH = 'FB_BABY_BATH';
  const FB_BABY_BLANKET = 'FB_BABY_BLANKET';
  const FB_BABY_DIAPER = 'FB_BABY_DIAPER';
  const FB_BABY_GIFT_SET = 'FB_BABY_GIFT_SET';
  const FB_BABY_HEALTH = 'FB_BABY_HEALTH';
  const FB_BABY_NURSING = 'FB_BABY_NURSING';
  const FB_BABY_POTTY_TRN = 'FB_BABY_POTTY_TRN';
  const FB_BABY_SAFE = 'FB_BABY_SAFE';
  const FB_BABY_TOYS = 'FB_BABY_TOYS';
  const FB_BABY_TRANSPORT = 'FB_BABY_TRANSPORT';
  const FB_BABY_TRANSPORT_ACC = 'FB_BABY_TRANSPORT_ACC';
  const FB_BAGS = 'FB_BAGS';
  const FB_BAGS_BKPK = 'FB_BAGS_BKPK';
  const FB_BAGS_BOXES = 'FB_BAGS_BOXES';
  const FB_BAGS_BRFCS = 'FB_BAGS_BRFCS';
  const FB_BAGS_CSMT_BAG = 'FB_BAGS_CSMT_BAG';
  const FB_BAGS_DFFL = 'FB_BAGS_DFFL';
  const FB_BAGS_DIPR = 'FB_BAGS_DIPR';
  const FB_BAGS_FNNY = 'FB_BAGS_FNNY';
  const FB_BAGS_GRMT = 'FB_BAGS_GRMT';
  const FB_BAGS_LUGG = 'FB_BAGS_LUGG';
  const FB_BAGS_LUG_ACC = 'FB_BAGS_LUG_ACC';
  const FB_BAGS_MSGR = 'FB_BAGS_MSGR';
  const FB_BAGS_TOTE = 'FB_BAGS_TOTE';
  const FB_BAGS_TRN_CAS = 'FB_BAGS_TRN_CAS';
  const FB_BLDG = 'FB_BLDG';
  const FB_BLDG_ACC = 'FB_BLDG_ACC';
  const FB_BLDG_CNSMB = 'FB_BLDG_CNSMB';
  const FB_BLDG_FENCE = 'FB_BLDG_FENCE';
  const FB_BLDG_FUEL_TNK = 'FB_BLDG_FUEL_TNK';
  const FB_BLDG_HT_VNT = 'FB_BLDG_HT_VNT';
  const FB_BLDG_LOCK = 'FB_BLDG_LOCK';
  const FB_BLDG_MATRL = 'FB_BLDG_MATRL';
  const FB_BLDG_PLMB = 'FB_BLDG_PLMB';
  const FB_BLDG_PUMP = 'FB_BLDG_PUMP';
  const FB_BLDG_PWRS = 'FB_BLDG_PWRS';
  const FB_BLDG_STR_TANK = 'FB_BLDG_STR_TANK';
  const FB_BLDG_S_ENG = 'FB_BLDG_S_ENG';
  const FB_BLDG_TL_ACC = 'FB_BLDG_TL_ACC';
  const FB_BLDG_TOOL = 'FB_BLDG_TOOL';
  const FB_BUSIND = 'FB_BUSIND';
  const FB_BUSIND_ADVERTISING = 'FB_BUSIND_ADVERTISING';
  const FB_BUSIND_AGRICULTURE = 'FB_BUSIND_AGRICULTURE';
  const FB_BUSIND_AUTOMATION = 'FB_BUSIND_AUTOMATION';
  const FB_BUSIND_HEAVY_MACH = 'FB_BUSIND_HEAVY_MACH';
  const FB_BUSIND_LAB = 'FB_BUSIND_LAB';
  const FB_BUSIND_MEDICAL = 'FB_BUSIND_MEDICAL';
  const FB_BUSIND_RETAIL = 'FB_BUSIND_RETAIL';
  const FB_BUSIND_SANITARY_CT = 'FB_BUSIND_SANITARY_CT';
  const FB_BUSIND_SIGN = 'FB_BUSIND_SIGN';
  const FB_BUSIND_STORAGE = 'FB_BUSIND_STORAGE';
  const FB_BUSIND_STORAGE_ACC = 'FB_BUSIND_STORAGE_ACC';
  const FB_BUSIND_WORK_GEAR = 'FB_BUSIND_WORK_GEAR';
  const FB_CAMERA_ACC = 'FB_CAMERA_ACC';
  const FB_CAMERA_CAMERA = 'FB_CAMERA_CAMERA';
  const FB_CAMERA_OPTIC = 'FB_CAMERA_OPTIC';
  const FB_CAMERA_OPTICS = 'FB_CAMERA_OPTICS';
  const FB_CAMERA_PHOTO = 'FB_CAMERA_PHOTO';
  const FB_ELEC = 'FB_ELEC';
  const FB_ELEC_ACC = 'FB_ELEC_ACC';
  const FB_ELEC_ARCDADE = 'FB_ELEC_ARCDADE';
  const FB_ELEC_AUDIO = 'FB_ELEC_AUDIO';
  const FB_ELEC_CIRCUIT = 'FB_ELEC_CIRCUIT';
  const FB_ELEC_COMM = 'FB_ELEC_COMM';
  const FB_ELEC_COMPUTER = 'FB_ELEC_COMPUTER';
  const FB_ELEC_GPS_ACC = 'FB_ELEC_GPS_ACC';
  const FB_ELEC_GPS_NAV = 'FB_ELEC_GPS_NAV';
  const FB_ELEC_GPS_TRK = 'FB_ELEC_GPS_TRK';
  const FB_ELEC_MARINE = 'FB_ELEC_MARINE';
  const FB_ELEC_NETWORK = 'FB_ELEC_NETWORK';
  const FB_ELEC_PART = 'FB_ELEC_PART';
  const FB_ELEC_PRINT = 'FB_ELEC_PRINT';
  const FB_ELEC_RADAR = 'FB_ELEC_RADAR';
  const FB_ELEC_SFTWR = 'FB_ELEC_SFTWR';
  const FB_ELEC_SPEED_RDR = 'FB_ELEC_SPEED_RDR';
  const FB_ELEC_TELEVISION = 'FB_ELEC_TELEVISION';
  const FB_ELEC_TOLL = 'FB_ELEC_TOLL';
  const FB_ELEC_VIDEO = 'FB_ELEC_VIDEO';
  const FB_ELEC_VID_GM_ACC = 'FB_ELEC_VID_GM_ACC';
  const FB_ELEC_VID_GM_CNSL = 'FB_ELEC_VID_GM_CNSL';
  const FB_FOOD = 'FB_FOOD';
  const FB_FURN = 'FB_FURN';
  const FB_FURN_BABY = 'FB_FURN_BABY';
  const FB_FURN_BENCH = 'FB_FURN_BENCH';
  const FB_FURN_CART = 'FB_FURN_CART';
  const FB_FURN_CHAIR = 'FB_FURN_CHAIR';
  const FB_FURN_CHAIR_ACC = 'FB_FURN_CHAIR_ACC';
  const FB_FURN_DIVIDE = 'FB_FURN_DIVIDE';
  const FB_FURN_DIVIDE_ACC = 'FB_FURN_DIVIDE_ACC';
  const FB_FURN_ENT_CTR = 'FB_FURN_ENT_CTR';
  const FB_FURN_FUTN = 'FB_FURN_FUTN';
  const FB_FURN_FUTN_PAD = 'FB_FURN_FUTN_PAD';
  const FB_FURN_OFFICE = 'FB_FURN_OFFICE';
  const FB_FURN_OFFICE_ACC = 'FB_FURN_OFFICE_ACC';
  const FB_FURN_OTTO = 'FB_FURN_OTTO';
  const FB_FURN_OUTDOOR = 'FB_FURN_OUTDOOR';
  const FB_FURN_OUTDOOR_ACC = 'FB_FURN_OUTDOOR_ACC';
  const FB_FURN_SETS = 'FB_FURN_SETS';
  const FB_FURN_SHELVE_ACC = 'FB_FURN_SHELVE_ACC';
  const FB_FURN_SHLF = 'FB_FURN_SHLF';
  const FB_FURN_SOFA = 'FB_FURN_SOFA';
  const FB_FURN_SOFA_ACC = 'FB_FURN_SOFA_ACC';
  const FB_FURN_STORAGE = 'FB_FURN_STORAGE';
  const FB_FURN_TABL = 'FB_FURN_TABL';
  const FB_FURN_TABL_ACC = 'FB_FURN_TABL_ACC';
  const FB_GENERIC_TAXABLE = 'FB_GENERIC_TAXABLE';
  const FB_HLTH = 'FB_HLTH';
  const FB_HLTH_HLTH = 'FB_HLTH_HLTH';
  const FB_HLTH_JWL_CR = 'FB_HLTH_JWL_CR';
  const FB_HLTH_LILP_BLM = 'FB_HLTH_LILP_BLM';
  const FB_HLTH_LTN_SPF = 'FB_HLTH_LTN_SPF';
  const FB_HLTH_PRSL_CR = 'FB_HLTH_PRSL_CR';
  const FB_HLTH_SKN_CR = 'FB_HLTH_SKN_CR';
  const FB_HMGN = 'FB_HMGN';
  const FB_HMGN_BATH = 'FB_HMGN_BATH';
  const FB_HMGN_DCOR = 'FB_HMGN_DCOR';
  const FB_HMGN_EMGY = 'FB_HMGN_EMGY';
  const FB_HMGN_FPLC = 'FB_HMGN_FPLC';
  const FB_HMGN_FPLC_ACC = 'FB_HMGN_FPLC_ACC';
  const FB_HMGN_GS_SFT = 'FB_HMGN_GS_SFT';
  const FB_HMGN_HS_ACC = 'FB_HMGN_HS_ACC';
  const FB_HMGN_HS_APP = 'FB_HMGN_HS_APP';
  const FB_HMGN_HS_SPL = 'FB_HMGN_HS_SPL';
  const FB_HMGN_KTCN = 'FB_HMGN_KTCN';
  const FB_HMGN_LAWN = 'FB_HMGN_LAWN';
  const FB_HMGN_LGHT = 'FB_HMGN_LGHT';
  const FB_HMGN_LINN = 'FB_HMGN_LINN';
  const FB_HMGN_LT_ACC = 'FB_HMGN_LT_ACC';
  const FB_HMGN_OTDR = 'FB_HMGN_OTDR';
  const FB_HMGN_POOL = 'FB_HMGN_POOL';
  const FB_HMGN_SCTY = 'FB_HMGN_SCTY';
  const FB_HMGN_SMK_ACC = 'FB_HMGN_SMK_ACC';
  const FB_HMGN_UMBR = 'FB_HMGN_UMBR';
  const FB_HMGN_UMBR_ACC = 'FB_HMGN_UMBR_ACC';
  const FB_MDIA = 'FB_MDIA';
  const FB_MDIA_BOOK = 'FB_MDIA_BOOK';
  const FB_MDIA_DVDS = 'FB_MDIA_DVDS';
  const FB_MDIA_MAG = 'FB_MDIA_MAG';
  const FB_MDIA_MANL = 'FB_MDIA_MANL';
  const FB_MDIA_MUSC = 'FB_MDIA_MUSC';
  const FB_MDIA_PRJ_PLN = 'FB_MDIA_PRJ_PLN';
  const FB_MDIA_SHT_MUS = 'FB_MDIA_SHT_MUS';
  const FB_OFFC = 'FB_OFFC';
  const FB_OFFC_BKAC = 'FB_OFFC_BKAC';
  const FB_OFFC_CRTS = 'FB_OFFC_CRTS';
  const FB_OFFC_DSKP = 'FB_OFFC_DSKP';
  const FB_OFFC_EQIP = 'FB_OFFC_EQIP';
  const FB_OFFC_FLNG = 'FB_OFFC_FLNG';
  const FB_OFFC_GNRL = 'FB_OFFC_GNRL';
  const FB_OFFC_INSTM = 'FB_OFFC_INSTM';
  const FB_OFFC_LP_DSK = 'FB_OFFC_LP_DSK';
  const FB_OFFC_MATS = 'FB_OFFC_MATS';
  const FB_OFFC_NM_PLT = 'FB_OFFC_NM_PLT';
  const FB_OFFC_PPR_HNDL = 'FB_OFFC_PPR_HNDL';
  const FB_OFFC_PRSNT_SPL = 'FB_OFFC_PRSNT_SPL';
  const FB_OFFC_SEALR = 'FB_OFFC_SEALR';
  const FB_OFFC_SHIP_SPL = 'FB_OFFC_SHIP_SPL';
  const FB_RLGN = 'FB_RLGN';
  const FB_RLGN_CMNY = 'FB_RLGN_CMNY';
  const FB_RLGN_ITEM = 'FB_RLGN_ITEM';
  const FB_RLGN_WEDD = 'FB_RLGN_WEDD';
  const FB_SFTWR = 'FB_SFTWR';
  const FB_SFWR_CMPTR = 'FB_SFWR_CMPTR';
  const FB_SFWR_DGTL_GD = 'FB_SFWR_DGTL_GD';
  const FB_SFWR_GAME = 'FB_SFWR_GAME';
  const FB_SHIPPING = 'FB_SHIPPING';
  const FB_SPOR = 'FB_SPOR';
  const FB_SPORT_ATHL = 'FB_SPORT_ATHL';
  const FB_SPORT_ATHL_CLTH = 'FB_SPORT_ATHL_CLTH';
  const FB_SPORT_ATHL_SHOE = 'FB_SPORT_ATHL_SHOE';
  const FB_SPORT_ATHL_SPRT = 'FB_SPORT_ATHL_SPRT';
  const FB_SPORT_EXRCS = 'FB_SPORT_EXRCS';
  const FB_SPORT_INDR_GM = 'FB_SPORT_INDR_GM';
  const FB_SPORT_OTDR_GM = 'FB_SPORT_OTDR_GM';
  const FB_TOYS = 'FB_TOYS';
  const FB_TOYS_EQIP = 'FB_TOYS_EQIP';
  const FB_TOYS_GAME = 'FB_TOYS_GAME';
  const FB_TOYS_PZZL = 'FB_TOYS_PZZL';
  const FB_TOYS_TMRS = 'FB_TOYS_TMRS';
  const FB_TOYS_TOYS = 'FB_TOYS_TOYS';
  const FB_VEHI = 'FB_VEHI';
  const FB_VEHI_PART = 'FB_VEHI_PART';
}
