<?php
 /*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 * All rights reserved.
 *
 * This source code is licensed under the license found in the
 * LICENSE file in the root directory of this source tree.
 */

namespace FacebookAds\Object\Values;

use FacebookAds\Enum\AbstractEnum;

/**
 * This class is auto-generated.
 *
 * For any issues or feature requests related to this class, please let us know
 * on github and we'll fix in our codegen framework. We'll not be able to accept
 * pull request for this class.
 *
 * @method static ProductCatalogVersionItemsBatchPostItemSubTypeValues getInstance()
 */
class ProductCatalogVersionItemsBatchPostItemSubTypeValues extends AbstractEnum {

  const APPLIANCES = 'APPLIANCES';
  const BABY_FEEDING = 'BABY_FEEDING';
  const BABY_TRANSPORT = 'BABY_TRANSPORT';
  const BEAUTY = 'BEAUTY';
  const BEDDING = 'BEDDING';
  const CAMERAS = 'CAMERAS';
  const CAMERAS_AND_PHOTOS = 'CAMERAS_AND_PHOTOS';
  const CELL_PHONES_AND_SMART_WATCHES = 'CELL_PHONES_AND_SMART_WATCHES';
  const CLEANING_SUPPLIES = 'CLEANING_SUPPLIES';
  const CLOTHING = 'CLOTHING';
  const CLOTHING_ACCESSORIES = 'CLOTHING_ACCESSORIES';
  const CLO_OFFER = 'CLO_OFFER';
  const COMPUTERS_AND_TABLETS = 'COMPUTERS_AND_TABLETS';
  const COMPUTERS_LAPTOPS_AND_TABLETS = 'COMPUTERS_LAPTOPS_AND_TABLETS';
  const COMPUTER_COMPONENTS = 'COMPUTER_COMPONENTS';
  const DIAPERING_AND_POTTY_TRAINING = 'DIAPERING_AND_POTTY_TRAINING';
  const ELECTRONICS_ACCESSORIES = 'ELECTRONICS_ACCESSORIES';
  const ELECTRONIC_ACCESSORIES_AND_CABLES = 'ELECTRONIC_ACCESSORIES_AND_CABLES';
  const VALUE_EMPTY = 'EMPTY';
  const FURNITURE = 'FURNITURE';
  const HEALTH = 'HEALTH';
  const HOME = 'HOME';
  const HOME_GOODS = 'HOME_GOODS';
  const HOUSEHOLD_AND_CLEANING_SUPPLIES = 'HOUSEHOLD_AND_CLEANING_SUPPLIES';
  const JEWELRY = 'JEWELRY';
  const LARGE_APPLIANCES = 'LARGE_APPLIANCES';
  const LOCAL_SERVICE_BUSINESS_ITEM = 'LOCAL_SERVICE_BUSINESS_ITEM';
  const LOCAL_SERVICE_BUSINESS_RESTAURANT = 'LOCAL_SERVICE_BUSINESS_RESTAURANT';
  const NURSERY = 'NURSERY';
  const PRINTERS_AND_SCANNERS = 'PRINTERS_AND_SCANNERS';
  const PRINTERS_SCANNERS_AND_FAX_MACHINES = 'PRINTERS_SCANNERS_AND_FAX_MACHINES';
  const PRODUCT_DISCOUNT = 'PRODUCT_DISCOUNT';
  const PROJECTORS = 'PROJECTORS';
  const SHOES = 'SHOES';
  const SHOES_AND_FOOTWEAR = 'SHOES_AND_FOOTWEAR';
  const SOFTWARE = 'SOFTWARE';
  const TELEVISIONS_AND_MONITORS = 'TELEVISIONS_AND_MONITORS';
  const TEST_CHILD_SUB_VERTICAL = 'TEST_CHILD_SUB_VERTICAL';
  const TEST_GRAND_CHILD_SUB_VERTICAL = 'TEST_GRAND_CHILD_SUB_VERTICAL';
  const TEST_SUB_VERTICAL = 'TEST_SUB_VERTICAL';
  const TEST_SUB_VERTICAL_ALIAS = 'TEST_SUB_VERTICAL_ALIAS';
  const TEST_SUB_VERTICAL_DATA_OBJECT = 'TEST_SUB_VERTICAL_DATA_OBJECT';
  const THIRD_PARTY_ELECTRONICS = 'THIRD_PARTY_ELECTRONICS';
  const THIRD_PARTY_TOYS_AND_GAMES = 'THIRD_PARTY_TOYS_AND_GAMES';
  const TOYS = 'TOYS';
  const TOYS_AND_GAMES = 'TOYS_AND_GAMES';
  const TVS_AND_MONITORS = 'TVS_AND_MONITORS';
  const VEHICLE_MANUFACTURER = 'VEHICLE_MANUFACTURER';
  const VIDEO_GAMES_AND_CONSOLES = 'VIDEO_GAMES_AND_CONSOLES';
  const VIDEO_GAME_CONSOLES_AND_VIDEO_GAMES = 'VIDEO_GAME_CONSOLES_AND_VIDEO_GAMES';
  const VIDEO_PROJECTORS = 'VIDEO_PROJECTORS';
  const WATCHES = 'WATCHES';
}
